//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.2503.
// 
namespace Claro.SisAct.Negocios.EbsCreditosWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsCreditosWSPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws")]
    public class EbsCreditosWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EbsCreditosWSService() {
            this.Url = "http://172.19.74.189:7903/EbsCreditosWS/ebsCreditosSB11";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ventas/ebscreditosws/evaluarCredito", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarDatosDCResponse", Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
        public ConsultarDatosDCResponse evaluarCredito([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")] ConsultarDatosDCRequest consultarDatosDCRequest) {
            object[] results = this.Invoke("evaluarCredito", new object[] {
                        consultarDatosDCRequest});
            return ((ConsultarDatosDCResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginevaluarCredito(ConsultarDatosDCRequest consultarDatosDCRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("evaluarCredito", new object[] {
                        consultarDatosDCRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsultarDatosDCResponse EndevaluarCredito(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsultarDatosDCResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class ConsultarDatosDCRequest {
        
        /// <remarks/>
        public AuditRequestType auditRequestType;
        
        /// <remarks/>
        public string tipoDocumento;
        
        /// <remarks/>
        public string nroDocumento;
        
        /// <remarks/>
        public string strRazonSocial;
        
        /// <remarks/>
        public string strNombres;
        
        /// <remarks/>
        public string strApePaterno;
        
        /// <remarks/>
        public string strApeMaterno;
        
        /// <remarks/>
        public string oficina;
        
        /// <remarks/>
        public BEUsuario objUsuario;
        
        /// <remarks/>
        public string flagConsulta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", IsNullable=false)]
        public ListaCamposOpcionalesObjetoResponseOpcional[] listaResponseOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class AuditRequestType {
        
        /// <remarks/>
        public string idTransaccion;
        
        /// <remarks/>
        public string ipAplicacion;
        
        /// <remarks/>
        public string nombreAplicacion;
        
        /// <remarks/>
        public string usuarioAplicacion;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class BEItemGenerico {
        
        /// <remarks/>
        public string codigo;
        
        /// <remarks/>
        public string codigo2;
        
        /// <remarks/>
        public string codigo3;
        
        /// <remarks/>
        public string codigo4;
        
        /// <remarks/>
        public string descripcion;
        
        /// <remarks/>
        public string descripcion2;
        
        /// <remarks/>
        public string estado;
        
        /// <remarks/>
        public string tipo;
        
        /// <remarks/>
        public System.Double monto;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool montoSpecified;
        
        /// <remarks/>
        public string valor;
        
        /// <remarks/>
        public int cantidad;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadSpecified;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class AuditResponseType {
        
        /// <remarks/>
        public string idTransaccion;
        
        /// <remarks/>
        public string codigoRespuesta;
        
        /// <remarks/>
        public string mensajeRespuesta;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class ConsultarDatosDCResponse {
        
        /// <remarks/>
        public AuditResponseType auditResponseType;
        
        /// <remarks/>
        public string idFila;
        
        /// <remarks/>
        public string cadena;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("listaCadena")]
        public string[] listaCadena;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("lista")]
        public BEItemGenerico[] lista;
        
        /// <remarks/>
        public string objeto;
        
        /// <remarks/>
        public bool boleano;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boleanoSpecified;
        
        /// <remarks/>
        public string tipoRespuesta;
        
        /// <remarks/>
        public bool estadoSession;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSessionSpecified;
        
        /// <remarks/>
        public bool error;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool errorSpecified;
        
        /// <remarks/>
        public string codigoError;
        
        /// <remarks/>
        public string descripcionError;
        
        /// <remarks/>
        public string mensaje;
        
        /// <remarks/>
        public string tipo;
        
        /// <remarks/>
        public string buroConsultado;
        
        /// <remarks/>
        public string flagConsulta;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoResponseOpcional", IsNullable=false)]
        public ListaCamposOpcionalesObjetoResponseOpcional[] listaResponseOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class ListaCamposOpcionalesObjetoResponseOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/ventas/ebscreditosws/ws/types")]
    public class BEUsuario {
        
        /// <remarks/>
        public long idUsuario;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified;
        
        /// <remarks/>
        public long idUsuarioSisact;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSisactSpecified;
        
        /// <remarks/>
        public string idVendedorSap;
        
        /// <remarks/>
        public string idCuentaRed;
        
        /// <remarks/>
        public string estadoAcceso;
        
        /// <remarks/>
        public string nombre;
        
        /// <remarks/>
        public string apellido_Pat;
        
        /// <remarks/>
        public string apellido_Mat;
        
        /// <remarks/>
        public string nombreCompleto;
        
        /// <remarks/>
        public string cadenaPerfil;
        
        /// <remarks/>
        public string cadenaOpcionesPagina;
        
        /// <remarks/>
        public bool perfil149;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool perfil149Specified;
        
        /// <remarks/>
        public string login;
        
        /// <remarks/>
        public string idArea;
        
        /// <remarks/>
        public string area;
        
        /// <remarks/>
        public string host;
        
        /// <remarks/>
        public string oficinaVenta;
        
        /// <remarks/>
        public string oficinaVentaDescripcion;
        
        /// <remarks/>
        public string canalVenta;
        
        /// <remarks/>
        public string canalVentaDescripcion;
        
        /// <remarks/>
        public string terminal;
        
        /// <remarks/>
        public string tipoOficina;
    }
}
