//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.ConsultaSeguridad {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ConsultaSeguridadSOAP", Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public class ConsultaSeguridad : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ConsultaSeguridad() {
            this.Url = "http://limdesosbv03.tim.com.pe:7909/Utilities_Services/Seguridad/Inquiry/Consulta" +
"Seguridad";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/leerOpcione" +
"sMenu", RequestNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", ResponseNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("errorCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string leerOpcionesMenu([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string idTransaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ipAplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string aplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long usuario, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long appCod, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long nivel, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long opcPadre, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errorMsg, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("menu", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out menuType[] cursor_Menu) {
            object[] results = this.Invoke("leerOpcionesMenu", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuario,
                        appCod,
                        nivel,
                        opcPadre});
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursor_Menu = ((menuType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginleerOpcionesMenu(string idTransaccion, string ipAplicacion, string aplicacion, long usuario, long appCod, long nivel, long opcPadre, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("leerOpcionesMenu", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuario,
                        appCod,
                        nivel,
                        opcPadre}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndleerOpcionesMenu(System.IAsyncResult asyncResult, out string idTransaccion, out string errorMsg, out menuType[] cursor_Menu) {
            object[] results = this.EndInvoke(asyncResult);
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursor_Menu = ((menuType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/verificaUsu" +
"ario", RequestNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", ResponseNamespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("errorCode", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string verificaUsuario([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] ref string idTransaccion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string ipAplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string aplicacion, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] string usuarioLogin, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] long appCod, [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] out string errorMsg, [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] [System.Xml.Serialization.XmlArrayItemAttribute("seguridad", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)] out seguridadType[] cursorSeguridad) {
            object[] results = this.Invoke("verificaUsuario", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuarioLogin,
                        appCod});
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursorSeguridad = ((seguridadType[])(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginverificaUsuario(string idTransaccion, string ipAplicacion, string aplicacion, string usuarioLogin, long appCod, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("verificaUsuario", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        aplicacion,
                        usuarioLogin,
                        appCod}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndverificaUsuario(System.IAsyncResult asyncResult, out string idTransaccion, out string errorMsg, out seguridadType[] cursorSeguridad) {
            object[] results = this.EndInvoke(asyncResult);
            idTransaccion = ((string)(results[1]));
            errorMsg = ((string)(results[2]));
            cursorSeguridad = ((seguridadType[])(results[3]));
            return ((string)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public class menuType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string AplicCod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcCodPad;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicCod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNivPad;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNiv;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicDes;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicAbrev;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNomPag;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicNumOrd;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string OpcicD1;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/utilitiesservices/seguridad/consultaseguridad/")]
    public class seguridadType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuacCod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string PerfcCod;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string UsuacCodVenSap;
    }
}
