//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
// 
namespace Claro.SisAct.Negocios.ConsultaNacionalidadWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="DAT_ConsultaNacionalidadSOAP11Binding", Namespace="http://claro.com.pe/esb/ventas/DAT_ConsultaNacionalidad/v1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Fault))]
    public class DAT_ConsultaNacionalidad_v1 :  Microsoft.Web.Services2.WebServicesClientProtocol{
        
        public HeaderRequestType HeaderRequest;
        
        public HeaderRequest headerRequest;
        
        public HeaderResponse headerResponse;
        
        public HeaderResponseType HeaderResponse;
        
        /// <remarks/>
        public DAT_ConsultaNacionalidad_v1() {
            this.Url = "http://localhost:8088/mockDAT_ConsultaNacionalidadSOAP11Binding";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("HeaderResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/ventas/DAT_ConsultaNacionalidad/v1/consultarNacionalidad", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarNacionalidadResponse", Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")]
        public consultarNacionalidadResponse consultarNacionalidad([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")] consultarNacionalidadRequest consultarNacionalidadRequest) {
            object[] results = this.Invoke("consultarNacionalidad", new object[] {
                        consultarNacionalidadRequest});
            return ((consultarNacionalidadResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultarNacionalidad(consultarNacionalidadRequest consultarNacionalidadRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultarNacionalidad", new object[] {
                        consultarNacionalidadRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public consultarNacionalidadResponse EndconsultarNacionalidad(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((consultarNacionalidadResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/")]
    [System.Xml.Serialization.XmlRootAttribute("headerRequest", Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/", IsNullable=false)]
    public class HeaderRequest : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string channel;
        
        /// <remarks/>
        public string idApplication;
        
        /// <remarks/>
        public string userApplication;
        
        /// <remarks/>
        public string userSession;
        
        /// <remarks/>
        public string idESBTransaction;
        
        /// <remarks/>
        public string idBusinessTransaction;
        
        /// <remarks/>
        public System.DateTime startDate;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool startDateSpecified;
        
        /// <remarks/>
        public object additionalNode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public class Detail {
        
        /// <remarks/>
        public string code;
        
        /// <remarks/>
        public string description;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ebs/xsd/CommonsException")]
    public class Fault {
        
        /// <remarks/>
        public string faultcode;
        
        /// <remarks/>
        public string faultstring;
        
        /// <remarks/>
        public string faultactor;
        
        /// <remarks/>
        public Detail detail;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/")]
    public class RequestOpcionalTypeRequestOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")]
    public class consultarNacionalidadRequest {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable=false)]
        public RequestOpcionalTypeRequestOpcional[] listaResquestOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/")]
    public class ResponseOpcionalTypeResponseOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")]
    public class Result {
        
        /// <remarks/>
        public string nacionalidad;
        
        /// <remarks/>
        public int codigo;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")]
    public class ResponseDataConsultarNacionalidad {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("result")]
        public Result[] result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", Namespace="http://claro.com.pe/esb/data/generico/opcionales/v1/", IsNullable=false)]
        public ResponseOpcionalTypeResponseOpcional[] listaResponseOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseStatus/v1/")]
    public class ResponseStatus {
        
        /// <remarks/>
        public int estado;
        
        /// <remarks/>
        public string codigoRespuesta;
        
        /// <remarks/>
        public string descripcionRespuesta;
        
        /// <remarks/>
        public string ubicacionError;
        
        /// <remarks/>
        public System.DateTime fecha;
        
        /// <remarks/>
        public string origen;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/ventas/consultaNacionalidad/sec/v1/consultarNacional" +
"idad/")]
    public class consultarNacionalidadResponse {
        
        /// <remarks/>
        public ResponseStatus responseStatus;
        
        /// <remarks/>
        public ResponseDataConsultarNacionalidad responseData;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public class StatusType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string type;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string code;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string message;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgid;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    public class ArgType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string key;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string value;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/")]
    [System.Xml.Serialization.XmlRootAttribute("headerResponse", Namespace="http://claro.com.pe/esb/data/commonBusinessEntities/claroGenericHeaders/v2/", IsNullable=false)]
    public class HeaderResponse : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string idESBTransaction;
        
        /// <remarks/>
        public string idBusinessTransaction;
        
        /// <remarks/>
        public System.DateTime startDate;
        
        /// <remarks/>
        public System.DateTime endDate;
        
        /// <remarks/>
        public object additionalNode;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    [System.Xml.Serialization.XmlRootAttribute("HeaderRequest", Namespace="http://claro.com.pe/generic/messageFormat/v1.0/", IsNullable=false)]
    public class HeaderRequestType : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string country;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string language;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consumer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string system;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string modulo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string userId;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string dispositivo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string wsIp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string operation;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string msgType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/generic/messageFormat/v1.0/")]
    [System.Xml.Serialization.XmlRootAttribute("HeaderResponse", Namespace="http://claro.com.pe/generic/messageFormat/v1.0/", IsNullable=false)]
    public class HeaderResponseType : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string consumer;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pid;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime timestamp;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timestampSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Arg", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public ArgType[] VarArg;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public StatusType Status;
    }
}
