'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace WS_INS
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EbsActDescPrepagoServiceSoapBinding", [Namespace]:="http://pe/com/claro/esb/services/activdesc/ws")>  _
    Public Class EbsActDescPrepagoService
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv03.tim.com.pe:8909/ActivarDesactivarPrepagoWS/EbsActDescPrepago"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/activdesc/ws", ResponseNamespace:="http://pe/com/claro/esb/services/activdesc/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarActivacion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")> ByVal INDatosLineaRequest As INDatosLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("INDatosLineaResponse", [Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")> INDatosLineaResponse
            Dim results() As Object = Me.Invoke("ejecutarActivacion", New Object() {INDatosLineaRequest})
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarActivacion(ByVal INDatosLineaRequest As INDatosLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarActivacion", New Object() {INDatosLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarActivacion(ByVal asyncResult As System.IAsyncResult) As INDatosLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe/com/claro/esb/services/activdesc/ws", ResponseNamespace:="http://pe/com/claro/esb/services/activdesc/ws", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarDesactivacion(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")> ByVal INDatosLineaRequest As INDatosLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("INDatosLineaResponse", [Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")> INDatosLineaResponse
            Dim results() As Object = Me.Invoke("ejecutarDesactivacion", New Object() {INDatosLineaRequest})
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarDesactivacion(ByVal INDatosLineaRequest As INDatosLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarDesactivacion", New Object() {INDatosLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarDesactivacion(ByVal asyncResult As System.IAsyncResult) As INDatosLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),INDatosLineaResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")>  _
    Public Class INDatosLineaRequest
        
        '<remarks/>
        Public telefono As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/actDescPrepago/schemas/ActDescPrepago")>  _
    Public Class INDatosLineaResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
End Namespace
