//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.DolWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsDolWSSoapBinding", Namespace="http://pe.com.claro.esb.services")]
    public class EbsDolWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EbsDolWS() {
            this.Url = "http://limdeseaiv03.tim.com.pe:8909/ServiceDolWS/EbsDolWS";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe.com.claro.esb.services", ResponseNamespace="http://pe.com.claro.esb.services", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("DOLResponse", Namespace="http://pe/com/claro/esb/services/clarify/schemas/dol/Clarify.xsd")]
        public DOLResponse dol([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/clarify/schemas/dol/Clarify.xsd")] DOLRequest DOLRequest) {
            object[] results = this.Invoke("dol", new object[] {
                        DOLRequest});
            return ((DOLResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult Begindol(DOLRequest DOLRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("dol", new object[] {
                        DOLRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public DOLResponse Enddol(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((DOLResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/clarify/schemas/dol/Clarify.xsd")]
    public class DOLRequest {
        
        /// <remarks/>
        public string nroTransaccion;
        
        /// <remarks/>
        public string msisdn;
        
        /// <remarks/>
        public string nombres;
        
        /// <remarks/>
        public string apellidos;
        
        /// <remarks/>
        public string tipoDocumento;
        
        /// <remarks/>
        public string numeroDocumento;
        
        /// <remarks/>
        public string telefonoReferencia;
        
        /// <remarks/>
        public string fechaNacimiento;
        
        /// <remarks/>
        public string lugarNacimiento;
        
        /// <remarks/>
        public string motivoRegistro;
        
        /// <remarks/>
        public string direccionCompleta;
        
        /// <remarks/>
        public string ciudad;
        
        /// <remarks/>
        public string codigoEmpleado;
        
        /// <remarks/>
        public string codigoSistema;
        
        /// <remarks/>
        public string tipo;
        
        /// <remarks/>
        public string texto;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/clarify/schemas/dol/Clarify.xsd")]
    public class DOLResponse {
        
        /// <remarks/>
        public string resultado;
        
        /// <remarks/>
        public string transaccion;
        
        /// <remarks/>
        public string descripcion;
    }
}
