//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.ActivacionVasWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ActivacionVASPortTypeSOAP11Binding", Namespace="http://claro.com.pe/eai/ebs/ws/vas/ActivacionVAS")]
    public class ebsActivacionVASService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ebsActivacionVASService() {
            this.Url = "http://limdeseaiocsv02.tim.com.pe:8909/ActivacionVASApp/ebsActivacionVAS";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/ebs/ws/vas/ActivacionVAS/activarServiciosVAS", RequestElementName="ActivacionVASRequest", RequestNamespace="http://claro.com.pe/eai/ebs/ws/vas/ActivacionVAS", ResponseElementName="ActivacionVASResponse", ResponseNamespace="http://claro.com.pe/eai/ebs/ws/vas/ActivacionVAS", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("codigoRespuesta")]
        public string activarServiciosVAS(ref string idTransaccion, string ipAplicacion, string nombreAplicacion, string msisdn, string imsi, string servicio, string tipoLinea, string nombreGrupo, string trama, out string mensajeRespuesta, out string estado) {
            object[] results = this.Invoke("activarServiciosVAS", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        nombreAplicacion,
                        msisdn,
                        imsi,
                        servicio,
                        tipoLinea,
                        nombreGrupo,
                        trama});
            idTransaccion = ((string)(results[1]));
            mensajeRespuesta = ((string)(results[2]));
            estado = ((string)(results[3]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginactivarServiciosVAS(string idTransaccion, string ipAplicacion, string nombreAplicacion, string msisdn, string imsi, string servicio, string tipoLinea, string nombreGrupo, string trama, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("activarServiciosVAS", new object[] {
                        idTransaccion,
                        ipAplicacion,
                        nombreAplicacion,
                        msisdn,
                        imsi,
                        servicio,
                        tipoLinea,
                        nombreGrupo,
                        trama}, callback, asyncState);
        }
        
        /// <remarks/>
        public string EndactivarServiciosVAS(System.IAsyncResult asyncResult, out string idTransaccion, out string mensajeRespuesta, out string estado) {
            object[] results = this.EndInvoke(asyncResult);
            idTransaccion = ((string)(results[1]));
            mensajeRespuesta = ((string)(results[2]));
            estado = ((string)(results[3]));
            return ((string)(results[0]));
        }
    }
}
