//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.ConsultaPostpagoWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SIACPostpagoConsultasWSServiceSoapBinding", Namespace="http://pe/com/claro/siacpostpago/ws")]
    public class SIACPostpagoConsultasWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public SIACPostpagoConsultasWSService() {
            this.Url = "http://limdeseaiv01:8903/SIACPostpagoWS/SIACPostpagoConsultasWS";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("compromisoPagoResponse", Namespace="http://claro.com/SIACPostpago/compromisoPago")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/compromisoPago", IsNullable=false)]
        public compromisoPago[] compromisoPago(string p_csid) {
            object[] results = this.Invoke("compromisoPago", new object[] {
                        p_csid});
            return ((compromisoPago[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegincompromisoPago(string p_csid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("compromisoPago", new object[] {
                        p_csid}, callback, asyncState);
        }
        
        /// <remarks/>
        public compromisoPago[] EndcompromisoPago(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((compromisoPago[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ConsultaTriadosResponse", Namespace="http://claro.com/SIACPostpago/ConsultaTriados")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/ConsultaTriados", IsNullable=false)]
        public ConsultaTriados[] consultaTriados(int p_coid) {
            object[] results = this.Invoke("consultaTriados", new object[] {
                        p_coid});
            return ((ConsultaTriados[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultaTriados(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultaTriados", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ConsultaTriados[] EndconsultaTriados(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ConsultaTriados[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("HistPlanLineaResponse", Namespace="http://claro.com/SIACPostpago/HistPlanLinea")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/HistPlanLinea", IsNullable=false)]
        public HistPlanLinea[] historicoPlanLinea(int p_coid) {
            object[] results = this.Invoke("historicoPlanLinea", new object[] {
                        p_coid});
            return ((HistPlanLinea[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhistoricoPlanLinea(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("historicoPlanLinea", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public HistPlanLinea[] EndhistoricoPlanLinea(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HistPlanLinea[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("obtenerDatosBscsExtResponse", Namespace="http://claro.com/SIACPostpago/obtenerDatosBscsExt")]
        public obtenerDatosBscsExtResponse ObtenerDatosBscsExt(string p_msisdn, int p_tmcode) {
            object[] results = this.Invoke("ObtenerDatosBscsExt", new object[] {
                        p_msisdn,
                        p_tmcode});
            return ((obtenerDatosBscsExtResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginObtenerDatosBscsExt(string p_msisdn, int p_tmcode, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("ObtenerDatosBscsExt", new object[] {
                        p_msisdn,
                        p_tmcode}, callback, asyncState);
        }
        
        /// <remarks/>
        public obtenerDatosBscsExtResponse EndObtenerDatosBscsExt(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((obtenerDatosBscsExtResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("historicoAccionesResponse", Namespace="http://claro.com/SIACPostpago/historicoAcciones")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/historicoAcciones", IsNullable=false)]
        public historicoAcciones[] historicoAcciones(string p_msisdn, string p_fecini, string p_fecfin) {
            object[] results = this.Invoke("historicoAcciones", new object[] {
                        p_msisdn,
                        p_fecini,
                        p_fecfin});
            return ((historicoAcciones[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhistoricoAcciones(string p_msisdn, string p_fecini, string p_fecfin, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("historicoAcciones", new object[] {
                        p_msisdn,
                        p_fecini,
                        p_fecfin}, callback, asyncState);
        }
        
        /// <remarks/>
        public historicoAcciones[] EndhistoricoAcciones(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((historicoAcciones[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("datosContratoResponse", Namespace="http://claro.com/SIACPostpago/DatosContrato")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/DatosContrato", IsNullable=false)]
        public contrato[] datosContrato(int p_coid) {
            object[] results = this.Invoke("datosContrato", new object[] {
                        p_coid});
            return ((contrato[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindatosContrato(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("datosContrato", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public contrato[] EnddatosContrato(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((contrato[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ListaFechaFacturaResponse", Namespace="http://claro.com/SIACPostpago/ListaFechaFactura")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/ListaFechaFactura", IsNullable=false)]
        public ListaFechaFactura[] listaFechaFactura(int p_csid, int p_ciclos) {
            object[] results = this.Invoke("listaFechaFactura", new object[] {
                        p_csid,
                        p_ciclos});
            return ((ListaFechaFactura[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistaFechaFactura(int p_csid, int p_ciclos, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listaFechaFactura", new object[] {
                        p_csid,
                        p_ciclos}, callback, asyncState);
        }
        
        /// <remarks/>
        public ListaFechaFactura[] EndlistaFechaFactura(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaFechaFactura[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ServiciosLineaResponse", Namespace="http://claro.com/SIACPostpago/ServiciosLinea")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/ServiciosLinea", IsNullable=false)]
        public ServiciosLinea[] serviciosLinea(int p_coid) {
            object[] results = this.Invoke("serviciosLinea", new object[] {
                        p_coid});
            return ((ServiciosLinea[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginserviciosLinea(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("serviciosLinea", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public ServiciosLinea[] EndserviciosLinea(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ServiciosLinea[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("penalidad_response", Namespace="http://claro.com/SIACPostpago/siga_penalidad_response.xsd")]
        public penalidad_response Penalidad([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com/SIACPostpago/siga_penalidad_request.xsd")] penalidad_request penalidad_request) {
            object[] results = this.Invoke("Penalidad", new object[] {
                        penalidad_request});
            return ((penalidad_response)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginPenalidad(penalidad_request penalidad_request, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("Penalidad", new object[] {
                        penalidad_request}, callback, asyncState);
        }
        
        /// <remarks/>
        public penalidad_response EndPenalidad(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((penalidad_response)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("ListaServiciosResponse", Namespace="http://claro.com/SIACPostpago/ListaServicios")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/ListaServicios", IsNullable=false)]
        public ListaServicios[] listaServicios() {
            object[] results = this.Invoke("listaServicios", new object[0]);
            return ((ListaServicios[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginlistaServicios(System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("listaServicios", new object[0], callback, asyncState);
        }
        
        /// <remarks/>
        public ListaServicios[] EndlistaServicios(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((ListaServicios[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("HistCambioSIMLineaResponse", Namespace="http://claro.com/SIACPostpago/HistCambioSIMLinea")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/HistCambioSIMLinea", IsNullable=false)]
        public HistCambioSIMLinea[] histCambioSIMLinea(int p_coid) {
            object[] results = this.Invoke("histCambioSIMLinea", new object[] {
                        p_coid});
            return ((HistCambioSIMLinea[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhistCambioSIMLinea(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("histCambioSIMLinea", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public HistCambioSIMLinea[] EndhistCambioSIMLinea(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HistCambioSIMLinea[])(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("datosClienteResponse", Namespace="http://claro.com/SIACPostpago/DatosCliente")]
        public datosClienteResponse datosCliente(string custcode, string dnnum) {
            object[] results = this.Invoke("datosCliente", new object[] {
                        custcode,
                        dnnum});
            return ((datosClienteResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BegindatosCliente(string custcode, string dnnum, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("datosCliente", new object[] {
                        custcode,
                        dnnum}, callback, asyncState);
        }
        
        /// <remarks/>
        public datosClienteResponse EnddatosCliente(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((datosClienteResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/siacpostpago/ws", ResponseNamespace="http://pe/com/claro/siacpostpago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute("HistEstadosLineaResponse", Namespace="http://claro.com/SIACPostpago/HistEstadosLinea")]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://claro.com/SIACPostpago/HistEstadosLinea", IsNullable=false)]
        public HistEstadosLinea[] historicoEstadoLinea(int p_coid) {
            object[] results = this.Invoke("historicoEstadoLinea", new object[] {
                        p_coid});
            return ((HistEstadosLinea[])(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginhistoricoEstadoLinea(int p_coid, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("historicoEstadoLinea", new object[] {
                        p_coid}, callback, asyncState);
        }
        
        /// <remarks/>
        public HistEstadosLinea[] EndhistoricoEstadoLinea(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((HistEstadosLinea[])(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/compromisoPago")]
    public class compromisoPago {
        
        /// <remarks/>
        public System.Single importe;
        
        /// <remarks/>
        public System.DateTime fecha_expiracion;
        
        /// <remarks/>
        public string usuario;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/HistEstadosLinea")]
    public class HistEstadosLinea {
        
        /// <remarks/>
        public string estado;
        
        /// <remarks/>
        public string motivo;
        
        /// <remarks/>
        public System.DateTime valido_desde;
        
        /// <remarks/>
        public System.DateTime introducido_el;
        
        /// <remarks/>
        public string introducido_por;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/DatosCliente")]
    public class cliente {
        
        /// <remarks/>
        public int customerId;
        
        /// <remarks/>
        public string cuenta;
        
        /// <remarks/>
        public string nombre;
        
        /// <remarks/>
        public string apellidos;
        
        /// <remarks/>
        public string razonSocial;
        
        /// <remarks/>
        public string tip_doc;
        
        /// <remarks/>
        public string num_doc;
        
        /// <remarks/>
        public string titulo;
        
        /// <remarks/>
        public string telef_principal;
        
        /// <remarks/>
        public string estado_civil;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date")]
        public System.DateTime fecha_nac;
        
        /// <remarks/>
        public string lug_nac;
        
        /// <remarks/>
        public string ruc_dni;
        
        /// <remarks/>
        public string nomb_comercial;
        
        /// <remarks/>
        public string contacto_cliente;
        
        /// <remarks/>
        public string rep_legal;
        
        /// <remarks/>
        public string telef_contacto;
        
        /// <remarks/>
        public string fax;
        
        /// <remarks/>
        public string email;
        
        /// <remarks/>
        public string cargo;
        
        /// <remarks/>
        public string consultor;
        
        /// <remarks/>
        public string asesor;
        
        /// <remarks/>
        public string direccion_fac;
        
        /// <remarks/>
        public string urbanizacion_fac;
        
        /// <remarks/>
        public string distrito_fac;
        
        /// <remarks/>
        public string provincia_fac;
        
        /// <remarks/>
        public string cod_postal_fac;
        
        /// <remarks/>
        public string departamento_fac;
        
        /// <remarks/>
        public string pais_fac;
        
        /// <remarks/>
        public string direccion_leg;
        
        /// <remarks/>
        public string urbanizacion_leg;
        
        /// <remarks/>
        public string distrito_leg;
        
        /// <remarks/>
        public string provincia_leg;
        
        /// <remarks/>
        public string cod_postal_leg;
        
        /// <remarks/>
        public string departamento_leg;
        
        /// <remarks/>
        public string pais_leg;
        
        /// <remarks/>
        public int co_id;
        
        /// <remarks/>
        public string nicho_id;
        
        /// <remarks/>
        public int num_cuentas;
        
        /// <remarks/>
        public int num_lineas;
        
        /// <remarks/>
        public string ciclo_fac;
        
        /// <remarks/>
        public string status_cuenta;
        
        /// <remarks/>
        public string modalidad;
        
        /// <remarks/>
        public string tipo_cliente;
        
        /// <remarks/>
        public System.DateTime fecha_act;
        
        /// <remarks/>
        public System.Single limite_credito;
        
        /// <remarks/>
        public string segmento;
        
        /// <remarks/>
        public string respon_pago;
        
        /// <remarks/>
        public string credit_score;
        
        /// <remarks/>
        public string forma_pago;
        
        /// <remarks/>
        public string codigo_tipo_cliente;
        
        /// <remarks/>
        public string sexo;
        
        /// <remarks/>
        public int nacionalidad;
        
        /// <remarks/>
        public int estado_civil_id;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/DatosCliente")]
    public class datosClienteResponse {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("cliente")]
        public cliente[] cliente;
        
        /// <remarks/>
        public string errorsql;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/HistCambioSIMLinea")]
    public class HistCambioSIMLinea {
        
        /// <remarks/>
        public string estado;
        
        /// <remarks/>
        public string motivo;
        
        /// <remarks/>
        public System.DateTime valido_desde;
        
        /// <remarks/>
        public string imsi;
        
        /// <remarks/>
        public string iccid;
        
        /// <remarks/>
        public System.DateTime introducido_el;
        
        /// <remarks/>
        public System.DateTime modificado_el;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/ListaServicios")]
    public class ListaServicios {
        
        /// <remarks/>
        public int codigo;
        
        /// <remarks/>
        public string servicio;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/siga_penalidad_response.xsd")]
    public class penalidad_response {
        
        /// <remarks/>
        public System.Single p_acuerdo_id_salida;
        
        /// <remarks/>
        public System.Single p_dias_pendientes;
        
        /// <remarks/>
        public System.Single p_cargo_fijo_diario;
        
        /// <remarks/>
        public System.Single p_precio_lista;
        
        /// <remarks/>
        public System.Single p_precio_venta;
        
        /// <remarks/>
        public System.Single p_monto_pcs;
        
        /// <remarks/>
        public System.Single p_monto_apadece;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/siga_penalidad_request.xsd")]
    public class penalidad_request {
        
        /// <remarks/>
        public System.Single p_acuerdo_id;
        
        /// <remarks/>
        public string p_nro_telefono;
        
        /// <remarks/>
        public System.DateTime p_fecha_penalidad;
        
        /// <remarks/>
        public System.Single p_numero_facturas;
        
        /// <remarks/>
        public System.Single p_cargo_fijo_act;
        
        /// <remarks/>
        public System.Single p_cargo_fijo_inf;
        
        /// <remarks/>
        public System.Single p_diasxmes;
        
        /// <remarks/>
        public System.Single p_codigo_plan_nuevo;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/ServiciosLinea")]
    public class ServiciosLinea {
        
        /// <remarks/>
        public string codigo;
        
        /// <remarks/>
        public string descripcion;
        
        /// <remarks/>
        public string estado;
        
        /// <remarks/>
        public System.DateTime fecha_estado;
        
        /// <remarks/>
        public System.DateTime fecha_solicitud;
        
        /// <remarks/>
        public string cuota;
        
        /// <remarks/>
        public string paquete;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/ListaFechaFactura")]
    public class ListaFechaFactura {
        
        /// <remarks/>
        public System.DateTime fec_emision;
        
        /// <remarks/>
        public System.DateTime fecha_inicio;
        
        /// <remarks/>
        public System.DateTime fecha_final;
        
        /// <remarks/>
        public string flag_facturado;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/DatosContrato")]
    public class contrato {
        
        /// <remarks/>
        public string telefono;
        
        /// <remarks/>
        public string estado;
        
        /// <remarks/>
        public string motivo;
        
        /// <remarks/>
        public System.DateTime fec_estado;
        
        /// <remarks/>
        public string plan;
        
        /// <remarks/>
        public string plazo_contrato;
        
        /// <remarks/>
        public string iccid;
        
        /// <remarks/>
        public string imsi;
        
        /// <remarks/>
        public string campania;
        
        /// <remarks/>
        public string p_venta;
        
        /// <remarks/>
        public string vendedor;
        
        /// <remarks/>
        public int co_id;
        
        /// <remarks/>
        public System.DateTime fecha_act;
        
        /// <remarks/>
        public string flag_plataforma;
        
        /// <remarks/>
        public string pin1;
        
        /// <remarks/>
        public string puk1;
        
        /// <remarks/>
        public string pin2;
        
        /// <remarks/>
        public string puk2;
        
        /// <remarks/>
        public int codigo_plan_tarifario;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/historicoAcciones")]
    public class historicoAcciones {
        
        /// <remarks/>
        public int contrato;
        
        /// <remarks/>
        public string descripcion;
        
        /// <remarks/>
        public string servicio;
        
        /// <remarks/>
        public string fecha;
        
        /// <remarks/>
        public string hora;
        
        /// <remarks/>
        public string usuario;
        
        /// <remarks/>
        public System.DateTime fech_orde;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/obtenerDatosBscsExt")]
    public class obtenerDatosBscsExtResponse {
        
        /// <remarks/>
        public System.Single p_num_fact;
        
        /// <remarks/>
        public System.Single p_cargo_fijo_act;
        
        /// <remarks/>
        public System.Single p_cargo_fijo_men;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/HistPlanLinea")]
    public class HistPlanLinea {
        
        /// <remarks/>
        public System.DateTime valido_desde;
        
        /// <remarks/>
        public string plan_tarifa;
        
        /// <remarks/>
        public string cambiado_por;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com/SIACPostpago/ConsultaTriados")]
    public class ConsultaTriados {
        
        /// <remarks/>
        public string tipo_triado;
        
        /// <remarks/>
        public int num_trio;
        
        /// <remarks/>
        public string telefono;
        
        /// <remarks/>
        public string factor;
        
        /// <remarks/>
        public string dest_trio;
        
        /// <remarks/>
        public string Cod_Tipo_Destino;
        
        /// <remarks/>
        public string Tipo_Destino;
    }
}
