//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.DatosPrepagoWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EbsDatosPrepagoServiceSoapBinding", Namespace="http://pe/com/claro/esb/services/consultaPrepago/ws")]
    public class EbsDatosPrepagoService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EbsDatosPrepagoService() {
            this.Url = "http://limdeseaiv03.tim.com.pe:8909/ConsultaDatosPrepagoWS/EbsDatosPrepago";
        }

		/// <Validacion KeepAlive/>
		protected override System.Net.WebRequest GetWebRequest(Uri uri)
		{
			System.Net.HttpWebRequest webRequest = (System.Net.HttpWebRequest) base.GetWebRequest(uri);
			webRequest.KeepAlive = false;
			return webRequest;
		}
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", ResponseNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("INDatosPrepagoResponse", Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public INDatosPrepagoResponse leerDatosPrepago([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")] INDatosPrepagoRequest INDatosPrepagoRequest) {
            object[] results = this.Invoke("leerDatosPrepago", new object[] {
                        INDatosPrepagoRequest});
            return ((INDatosPrepagoResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginleerDatosPrepago(INDatosPrepagoRequest INDatosPrepagoRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("leerDatosPrepago", new object[] {
                        INDatosPrepagoRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public INDatosPrepagoResponse EndleerDatosPrepago(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((INDatosPrepagoResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", ResponseNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("INDatosLineaResponse", Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
        public INDatosLineaResponse leerEstado([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")] INDatosLineaRequest INDatosLineaRequest) {
            object[] results = this.Invoke("leerEstado", new object[] {
                        INDatosLineaRequest});
            return ((INDatosLineaResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginleerEstado(INDatosLineaRequest INDatosLineaRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("leerEstado", new object[] {
                        INDatosLineaRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public INDatosLineaResponse EndleerEstado(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((INDatosLineaResponse)(results[0]));
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", ResponseNamespace="http://pe/com/claro/esb/services/consultaPrepago/ws", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("INSaldosBolsasResponse", Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
        public INSaldosBolsasResponse leerSaldosBolsas([System.Xml.Serialization.XmlElementAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")] INSaldosBolsasRequest INSaldosBolsasRequest) {
            object[] results = this.Invoke("leerSaldosBolsas", new object[] {
                        INSaldosBolsasRequest});
            return ((INSaldosBolsasResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginleerSaldosBolsas(INSaldosBolsasRequest INSaldosBolsasRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("leerSaldosBolsas", new object[] {
                        INSaldosBolsasRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public INSaldosBolsasResponse EndleerSaldosBolsas(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((INSaldosBolsasResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class INDatosPrepagoRequest {
        
        /// <remarks/>
        public string telefono;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public class SaldosBolsas {
        
        /// <remarks/>
        public string isFirstCalled;
        
        /// <remarks/>
        public string isLocked;
        
        /// <remarks/>
        public string expiryDate;
        
        /// <remarks/>
        public string deletionDate;
        
        /// <remarks/>
        public string onPeakAccountIdBalance;
        
        /// <remarks/>
        public string onPeakAccountIdExpiryDate;
        
        /// <remarks/>
        public string smsPromoAccountIdBalance;
        
        /// <remarks/>
        public string smsPromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string voice1PromoAccountIdBalance;
        
        /// <remarks/>
        public string voice1PromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string voice2PromoAccountIdBalance;
        
        /// <remarks/>
        public string voice2PromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string gprsPromoAccountIdBalance;
        
        /// <remarks/>
        public string gprsPromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string mmsPromoAccountIdBalance;
        
        /// <remarks/>
        public string mmsPromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string bonusPromoAccountIdBalance;
        
        /// <remarks/>
        public string bonusPromoAccountIdExpiryDate;
        
        /// <remarks/>
        public string smsLoyaltyAccountIdBalance;
        
        /// <remarks/>
        public string smsLoyaltyAccountIdExpiryDate;
        
        /// <remarks/>
        public string voiceLoyaltyAccountIdBalance;
        
        /// <remarks/>
        public string voiceLoyaltyAccountIdExpiryDate;
        
        /// <remarks/>
        public string gprsLoyaltyAccountIdBalance;
        
        /// <remarks/>
        public string gprsLoyaltyAccountIdExpiryDate;
        
        /// <remarks/>
        public string mmsLoyaltyAccountIdBalance;
        
        /// <remarks/>
        public string mmsLoyaltyAccountIdExpiryDate;
        
        /// <remarks/>
        public string bonusCounter_Account54Balance;
        
        /// <remarks/>
        public string bonusCounter_Account54ExpiryDate;
        
        /// <remarks/>
        public string isSelect;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public class INSaldosBolsasResponse {
        
        /// <remarks/>
        public string descripcion;
        
        /// <remarks/>
        public string resultado;
        
        /// <remarks/>
        public string transaccion;
        
        /// <remarks/>
        public SaldosBolsas saldosBolsas;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InSaldoBolsas")]
    public class INSaldosBolsasRequest {
        
        /// <remarks/>
        public string telefono;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class DatosLinea {
        
        /// <remarks/>
        public string providerID;
        
        /// <remarks/>
        public string isFirstCallPassed;
        
        /// <remarks/>
        public string isLocked;
        
        /// <remarks/>
        public string subscriberLifeCycleStatus;
        
        /// <remarks/>
        public string subscriberStatus;
        
        /// <remarks/>
        public string expiryDate;
        
        /// <remarks/>
        public string deletionDate;
        
        /// <remarks/>
        public string isSelect;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class INDatosLineaResponse {
        
        /// <remarks/>
        public string mensaje;
        
        /// <remarks/>
        public string resultado;
        
        /// <remarks/>
        public string transaccion;
        
        /// <remarks/>
        public DatosLinea datosLinea;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class INDatosLineaRequest {
        
        /// <remarks/>
        public string telefono;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class DatosPrepago {
        
        /// <remarks/>
        public string customerID;
        
        /// <remarks/>
        public string cgpa;
        
        /// <remarks/>
        public string providerID;
        
        /// <remarks/>
        public string useTestEnvironment;
        
        /// <remarks/>
        public string activeFnFOption;
        
        /// <remarks/>
        public string isLocked;
        
        /// <remarks/>
        public string isLockedForPeriodicRecharge;
        
        /// <remarks/>
        public string planGroupID;
        
        /// <remarks/>
        public string isFirstCallPassed;
        
        /// <remarks/>
        public string subscriberLifeCycleStatus;
        
        /// <remarks/>
        public string firstCallDate;
        
        /// <remarks/>
        public string rechargingPeriod;
        
        /// <remarks/>
        public string expiryDate;
        
        /// <remarks/>
        public string deletionDate;
        
        /// <remarks/>
        public string isFnFPossible;
        
        /// <remarks/>
        public string userGroup0;
        
        /// <remarks/>
        public string userGroup1;
        
        /// <remarks/>
        public string fnFNumber0;
        
        /// <remarks/>
        public string fnFNumber1;
        
        /// <remarks/>
        public string fnFNumber2;
        
        /// <remarks/>
        public string fnFNumber3;
        
        /// <remarks/>
        public string fnFNumber4;
        
        /// <remarks/>
        public string fnFNumber5;
        
        /// <remarks/>
        public string fnFNumber6;
        
        /// <remarks/>
        public string fnFNumber7;
        
        /// <remarks/>
        public string fnFNumber8;
        
        /// <remarks/>
        public string tariffModelNumber;
        
        /// <remarks/>
        public string postpaid;
        
        /// <remarks/>
        public string subscriberStatus;
        
        /// <remarks/>
        public string subscriberLastStatus;
        
        /// <remarks/>
        public string statusChangeDate;
        
        /// <remarks/>
        public string onPeakAccountIDBalance;
        
        /// <remarks/>
        public string onPeakAccountIDExpiryDate;
        
        /// <remarks/>
        public string sMSLoyaltyAccountIDBalance;
        
        /// <remarks/>
        public string sMSLoyaltyAccountIDExpiryDate;
        
        /// <remarks/>
        public string voiceLoyaltyAccountIDBalance;
        
        /// <remarks/>
        public string voiceLoyaltyAccountIDExpiryDate;
        
        /// <remarks/>
        public string gPRSLoyaltyAccountIDBalance;
        
        /// <remarks/>
        public string gPRSLoyaltyAccountIDExpiryDate;
        
        /// <remarks/>
        public string sMSPromoAccountIDBalance;
        
        /// <remarks/>
        public string sMSPromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string voice1PromoAccountIDBalance;
        
        /// <remarks/>
        public string voice1PromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string voice2PromoAccountIDBalance;
        
        /// <remarks/>
        public string voice2PromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string gPRSPromoAccountIDBalance;
        
        /// <remarks/>
        public string gPRSPromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string bonusPromoAccountIDBalance;
        
        /// <remarks/>
        public string bonusPromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string mMSLoyaltyAccountIDBalance;
        
        /// <remarks/>
        public string mMSLoyaltyAccountIDExpiryDate;
        
        /// <remarks/>
        public string mMSPromoAccountIDBalance;
        
        /// <remarks/>
        public string mMSPromoAccountIDExpiryDate;
        
        /// <remarks/>
        public string bonusCounter_Account54Balance;
        
        /// <remarks/>
        public string bonusCounter_Account54ExpiryDate;
        
        /// <remarks/>
        public string voucherRchFraudCounter;
        
        /// <remarks/>
        public string counterChangeFnFnoForFree;
        
        /// <remarks/>
        public string counterChangeFAnoForFree;
        
        /// <remarks/>
        public string counterChangeHZInoForFree;
        
        /// <remarks/>
        public string counterSubscribeFAForFree;
        
        /// <remarks/>
        public string counterSubscribeFnFForFree;
        
        /// <remarks/>
        public string counterSubscribeHZIForFree;
        
        /// <remarks/>
        public string counterSubscribeMLCForFree;
        
        /// <remarks/>
        public string counterChangeTariffForFree;
        
        /// <remarks/>
        public string cNTNumber;
        
        /// <remarks/>
        public string isCNTPossible;
        
        /// <remarks/>
        public string imsi;
        
        /// <remarks/>
        public string isSelect;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://pe/com/claro/esb/services/schemas/InDatosPrepago")]
    public class INDatosPrepagoResponse {
        
        /// <remarks/>
        public string descripcion;
        
        /// <remarks/>
        public string resultado;
        
        /// <remarks/>
        public string transaccion;
        
        /// <remarks/>
        public DatosPrepago datosPrePago;
    }
}
