//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.573
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=1.1.4322.573.
// 
namespace Claro.SisAct.Negocios.LineasTecnologiaClienteWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="consultarLineasPrePostSOAP11Binding", Namespace="http://claro.com.pe/esb/venta/lineastecnologiacliente/v1/")]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(ClaroFault))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(auditResponseType))]
    public class MED_LineasTecnologiaCliente : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        public HeaderRequestType headerRequest;
        
        public HeaderResponseType headerResponse;
        
        /// <remarks/>
        public MED_LineasTecnologiaCliente() {
            this.Url = "http://172.17.26.51:21000/BSS_LineasTecnologiaCliente/SRV_LineasTecnologiaCliente" +
"/Service/Mediation/MED_LineasTecnologiaCliente";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerRequest")]
        [System.Web.Services.Protocols.SoapHeaderAttribute("headerResponse", Direction=System.Web.Services.Protocols.SoapHeaderDirection.Out)]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/esb/venta/lineastecnologiacliente/v1/consultarLineasPrePost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarLineasPrePostResponse", Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")]
        public consultarLineasPrePostResponseType consultarLineasPrePost([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")] consultarLineasPrePostRequestType consultarLineasPrePostRequest) {
            object[] results = this.Invoke("consultarLineasPrePost", new object[] {
                        consultarLineasPrePostRequest});
            return ((consultarLineasPrePostResponseType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultarLineasPrePost(consultarLineasPrePostRequestType consultarLineasPrePostRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultarLineasPrePost", new object[] {
                        consultarLineasPrePostRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public consultarLineasPrePostResponseType EndconsultarLineasPrePost(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((consultarLineasPrePostResponseType)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("headerRequest", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable=false)]
    public class HeaderRequestType : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string canal;
        
        /// <remarks/>
        public long idAplicacion;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idAplicacionSpecified;
        
        /// <remarks/>
        public string usuarioAplicacion;
        
        /// <remarks/>
        public string usuarioSesion;
        
        /// <remarks/>
        public string idTransaccionESB;
        
        /// <remarks/>
        public string idTransaccionNegocio;
        
        /// <remarks/>
        public System.DateTime fechaInicio;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaInicioSpecified;
        
        /// <remarks/>
        public object nodoAdicional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroFault/v1/")]
    public class ClaroFault {
        
        /// <remarks/>
        public string idAuditoria;
        
        /// <remarks/>
        public string codigoError;
        
        /// <remarks/>
        public string descripcionError;
        
        /// <remarks/>
        public string ubicacionError;
        
        /// <remarks/>
        public System.DateTime fecha;
        
        /// <remarks/>
        public object errorOrigen;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataConsultarLineasPrePost/v1/")]
    public class auditResponseType {
        
        /// <remarks/>
        public string idTransaccion;
        
        /// <remarks/>
        public string codigoRespuesta;
        
        /// <remarks/>
        public string mensajeRespuesta;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataConsultarLineasPrePost/v1/")]
    public class ListaLineaTypeListaLineas {
        
        /// <remarks/>
        public string linea;
        
        /// <remarks/>
        public string planLinea;
        
        /// <remarks/>
        public string estadoLinea;
        
        /// <remarks/>
        public string tipoBloqueo;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/responseDataConsultarLineasPrePost/v1/")]
    public class responseDataConsultarLineasPrePostType {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("listaLineas", IsNullable=false)]
        public ListaLineaTypeListaLineas[] listaLineasType;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")]
    public class ResponseStatus {
        
        /// <remarks/>
        public int estado;
        
        /// <remarks/>
        public string codigoRespuesta;
        
        /// <remarks/>
        public string descripcionRespuesta;
        
        /// <remarks/>
        public string ubicacionError;
        
        /// <remarks/>
        public System.DateTime fecha;
        
        /// <remarks/>
        public string origen;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")]
    public class consultarLineasPrePostResponseType {
        
        /// <remarks/>
        public ResponseStatus responseStatus;
        
        /// <remarks/>
        public responseDataConsultarLineasPrePostType responseDataConsultarLineasPrePost;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", IsNullable=false)]
        public ParametrosTypeObjetoOpcional[] listaResponseOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")]
    public class ParametrosTypeObjetoOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string clave;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/message/lineastecnologiacliente/consultarLineasPrePost/v1" +
"/")]
    public class consultarLineasPrePostRequestType {
        
        /// <remarks/>
        public string tipoDocumento;
        
        /// <remarks/>
        public string numeroDocumento;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("objetoOpcional", IsNullable=false)]
        public ParametrosTypeObjetoOpcional[] listaRequestOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/")]
    [System.Xml.Serialization.XmlRootAttribute("headerResponse", Namespace="http://claro.com.pe/esb/data/generico/claroGenericHeader/v1/", IsNullable=false)]
    public class HeaderResponseType : System.Web.Services.Protocols.SoapHeader {
        
        /// <remarks/>
        public string idTransaccionESB;
        
        /// <remarks/>
        public string idTransaccionNegocio;
        
        /// <remarks/>
        public System.DateTime fechaInicio;
        
        /// <remarks/>
        public System.DateTime fechaFin;
        
        /// <remarks/>
        public object nodoAdicional;
    }
}
