//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
// 
namespace Claro.SisAct.Negocios.ClienteProteccionMovilWS {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ClienteProteccionMovilWSSB11", Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws")]
    public class ClienteProteccionMovilWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public ClienteProteccionMovilWSService() {
            this.Url = "http://limdeseaiv28.tim.com.pe:8909/ClienteProteccionMovilWS/ClienteProteccionMov" +
"ilWSSB11";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/services/clienteproteccionmovilws/consultarPrima", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Bare)]
        [return: System.Xml.Serialization.XmlElementAttribute("consultarPrimaResponse", Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")]
        public consultarPrimaResponse consultarPrima([System.Xml.Serialization.XmlElementAttribute(Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")] consultarPrimaRequest consultarPrimaRequest) {
            object[] results = this.Invoke("consultarPrima", new object[] {
                        consultarPrimaRequest});
            return ((consultarPrimaResponse)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginconsultarPrima(consultarPrimaRequest consultarPrimaRequest, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("consultarPrima", new object[] {
                        consultarPrimaRequest}, callback, asyncState);
        }
        
        /// <remarks/>
        public consultarPrimaResponse EndconsultarPrima(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((consultarPrimaResponse)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")]
    public class consultarPrimaRequest {
        
        /// <remarks/>
        public AuditRequestType auditRequest;
        
        /// <remarks/>
        public string accountType;
        
        /// <remarks/>
        public IdentificationType identificationType;
        
        /// <remarks/>
        public string clientProductSKU;
        
        /// <remarks/>
        public string clientAssetSKU;
        
        /// <remarks/>
        public string region;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("requestOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public RequestOpcionalTypeRequestOpcional[] listaRequestOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public class AuditRequestType {
        
        /// <remarks/>
        public string idTransaccion;
        
        /// <remarks/>
        public string ipAplicacion;
        
        /// <remarks/>
        public string aplicacion;
        
        /// <remarks/>
        public string usrAplicacion;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public class ResponseOpcionalTypeResponseOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")]
    public class ProductsProduct {
        
        /// <remarks/>
        public string productName;
        
        /// <remarks/>
        public string productDescription;
        
        /// <remarks/>
        public string incidentType;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string premium;
        
        /// <remarks/>
        public string deductible;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public class AuditResponseType {
        
        /// <remarks/>
        public string idTransaccion;
        
        /// <remarks/>
        public string codigoRespuesta;
        
        /// <remarks/>
        public string mensajeRespuesta;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")]
    public class consultarPrimaResponse {
        
        /// <remarks/>
        public AuditResponseType auditResponse;
        
        /// <remarks/>
        public string quoteID;
        
        /// <remarks/>
        public string nationalID;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("Product", IsNullable=false)]
        public ProductsProduct[] products;
        
        /// <remarks/>
        public string result;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("responseOpcional", Namespace="http://claro.com.pe/eai/ws/baseschema", IsNullable=false)]
        public ResponseOpcionalTypeResponseOpcional[] listaResponseOpcional;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/baseschema")]
    public class RequestOpcionalTypeRequestOpcional {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string campo;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string valor;
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/ws/clienteproteccionmovilws/types")]
    public class IdentificationType {
        
        /// <remarks/>
        public string idType;
        
        /// <remarks/>
        public string idValue;
        
        /// <remarks/>
        public string issuedCountryCode;
    }
}
