//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2503
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2503.
// 
namespace Claro.SisAct.Negocios.WSMail {
    using System.Diagnostics;
    using System.Xml.Serialization;
    using System;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="EnvioMailSOAP", Namespace="http://claro.com.pe/eai/messagingservices/mail/enviomail/")]
    public class EnvioMail : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        /// <remarks/>
        public EnvioMail() {
            this.Url = "http://172.19.74.141:8901/Messaging_Services/MAIL/Transaction/EnvioMail";
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://claro.com.pe/eai/messagingservices/mail/enviomail/envioMail", RequestNamespace="http://claro.com.pe/eai/messagingservices/mail/enviomail/", ResponseNamespace="http://claro.com.pe/eai/messagingservices/mail/enviomail/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("audit")]
        public AuditType envioMail(string txId, string ipApp, string usrApp, string remitente, string destinatario, string asunto, string mensaje, int flagHtml) {
            object[] results = this.Invoke("envioMail", new object[] {
                        txId,
                        ipApp,
                        usrApp,
                        remitente,
                        destinatario,
                        asunto,
                        mensaje,
                        flagHtml});
            return ((AuditType)(results[0]));
        }
        
        /// <remarks/>
        public System.IAsyncResult BeginenvioMail(string txId, string ipApp, string usrApp, string remitente, string destinatario, string asunto, string mensaje, int flagHtml, System.AsyncCallback callback, object asyncState) {
            return this.BeginInvoke("envioMail", new object[] {
                        txId,
                        ipApp,
                        usrApp,
                        remitente,
                        destinatario,
                        asunto,
                        mensaje,
                        flagHtml}, callback, asyncState);
        }
        
        /// <remarks/>
        public AuditType EndenvioMail(System.IAsyncResult asyncResult) {
            object[] results = this.EndInvoke(asyncResult);
            return ((AuditType)(results[0]));
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://claro.com.pe/eai/servicecommons/")]
    public class AuditType {
        
        /// <remarks/>
        public string txId;
        
        /// <remarks/>
        public string errorCode;
        
        /// <remarks/>
        public string errorMsg;
    }
}
