
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  public class ZES_PAGOSTable : SAPTable 
  {
    public static Type GetElementType() 
    {
        return (typeof(ZES_PAGOS));
    }
 
    public override object CreateNewRow()
    { 
        return new ZES_PAGOS();
    }
     
    public ZES_PAGOS this[int index] 
    {
        get 
        {
            return ((ZES_PAGOS)(List[index]));
        }
        set 
        {
            List[index] = value;
        }
    }
        
    public int Add(ZES_PAGOS value) 
    {
        return List.Add(value);
    }
        
    public void Insert(int index, ZES_PAGOS value) 
    {
        List.Insert(index, value);
    }
        
    public int IndexOf(ZES_PAGOS value) 
    {
        return List.IndexOf(value);
    }
        
    public bool Contains(ZES_PAGOS value) 
    {
        return List.Contains(value);
    }
        
    public void Remove(ZES_PAGOS value) 
    {
        List.Remove(value);
    }
        
    public void CopyTo(ZES_PAGOS[] array, int index) 
    {
        List.CopyTo(array, index);
	}
  }
}
