
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 13/07/2012
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_PLAN_TARIFARIO" , Length = 54)]
  public class ZST_PV_PLAN_TARIFARIO : SAPStructure
  {
    
    [RfcField(AbapName = "PLAN_TARIFARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 0)]
    [XmlElement("PLAN_TARIFARIO")]
    public string Plan_Tarifario
    { 
       get
       {
          return _Plan_Tarifario;
       }
       set
       {
          _Plan_Tarifario = value;
       }
    }
    private string _Plan_Tarifario;

    [RfcField(AbapName = "DESCRIPCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 3)]
    [XmlElement("DESCRIPCION")]
    public string Descripcion
    { 
       get
       {
          return _Descripcion;
       }
       set
       {
          _Descripcion = value;
       }
    }
    private string _Descripcion;

    [RfcField(AbapName = "FLAG_VIGENCIA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 43)]
    [XmlElement("FLAG_VIGENCIA")]
    public string Flag_Vigencia
    { 
       get
       {
          return _Flag_Vigencia;
       }
       set
       {
          _Flag_Vigencia = value;
       }
    }
    private string _Flag_Vigencia;

    [RfcField(AbapName = "CARGO_FIJO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 44)]
    [XmlElement("CARGO_FIJO")]
    public Decimal Cargo_Fijo
    { 
       get
       {
          return _Cargo_Fijo;
       }
       set
       {
          _Cargo_Fijo = value;
       }
    }
    private Decimal _Cargo_Fijo;

    [RfcField(AbapName = "TIPO_CLI_ACT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 52)]
    [XmlElement("TIPO_CLI_ACT")]
    public string Tipo_Cli_Act
    { 
       get
       {
          return _Tipo_Cli_Act;
       }
       set
       {
          _Tipo_Cli_Act = value;
       }
    }
    private string _Tipo_Cli_Act;

  }

}
