
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_HISTORICO_ACUERDO" , Length = 1598)]
  public class ZST_PV_HISTORICO_ACUERDO : SAPStructure
  {
    
    [RfcField(AbapName = "OFICINA_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 0)]
    [XmlElement("OFICINA_VENTA")]
    public string Oficina_Venta
    { 
       get
       {
          return _Oficina_Venta;
       }
       set
       {
          _Oficina_Venta = value;
       }
    }
    private string _Oficina_Venta;

    [RfcField(AbapName = "DES_OF_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 4)]
    [XmlElement("DES_OF_VENTA")]
    public string Des_Of_Venta
    { 
       get
       {
          return _Des_Of_Venta;
       }
       set
       {
          _Des_Of_Venta = value;
       }
    }
    private string _Des_Of_Venta;

    [RfcField(AbapName = "NUMERO_CONTRATO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 24)]
    [XmlElement("NUMERO_CONTRATO")]
    public string Numero_Contrato
    { 
       get
       {
          return _Numero_Contrato;
       }
       set
       {
          _Numero_Contrato = value;
       }
    }
    private string _Numero_Contrato;

    [RfcField(AbapName = "NUMERO_PCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 34)]
    [XmlElement("NUMERO_PCS")]
    public string Numero_Pcs
    { 
       get
       {
          return _Numero_Pcs;
       }
       set
       {
          _Numero_Pcs = value;
       }
    }
    private string _Numero_Pcs;

    [RfcField(AbapName = "CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 64)]
    [XmlElement("CLIENTE")]
    public string Cliente
    { 
       get
       {
          return _Cliente;
       }
       set
       {
          _Cliente = value;
       }
    }
    private string _Cliente;

    [RfcField(AbapName = "NOMBRE_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 80)]
    [XmlElement("NOMBRE_CLIENTE")]
    public string Nombre_Cliente
    { 
       get
       {
          return _Nombre_Cliente;
       }
       set
       {
          _Nombre_Cliente = value;
       }
    }
    private string _Nombre_Cliente;

    [RfcField(AbapName = "ESTADO_ASIGNACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 120)]
    [XmlElement("ESTADO_ASIGNACION")]
    public string Estado_Asignacion
    { 
       get
       {
          return _Estado_Asignacion;
       }
       set
       {
          _Estado_Asignacion = value;
       }
    }
    private string _Estado_Asignacion;

    [RfcField(AbapName = "USUARIO_ASIGNACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 121)]
    [XmlElement("USUARIO_ASIGNACION")]
    public string Usuario_Asignacion
    { 
       get
       {
          return _Usuario_Asignacion;
       }
       set
       {
          _Usuario_Asignacion = value;
       }
    }
    private string _Usuario_Asignacion;

    [RfcField(AbapName = "NOMUSU_ASIGNACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 131)]
    [XmlElement("NOMUSU_ASIGNACION")]
    public string Nomusu_Asignacion
    { 
       get
       {
          return _Nomusu_Asignacion;
       }
       set
       {
          _Nomusu_Asignacion = value;
       }
    }
    private string _Nomusu_Asignacion;

    [RfcField(AbapName = "FECHA_ASIGNACION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 171)]
    [XmlElement("FECHA_ASIGNACION")]
    public string Fecha_Asignacion
    { 
       get
       {
          return _Fecha_Asignacion;
       }
       set
       {
          _Fecha_Asignacion = value;
       }
    }
    private string _Fecha_Asignacion;

    [RfcField(AbapName = "HORA_ASIGNACION", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 179)]
    [XmlElement("HORA_ASIGNACION")]
    public string Hora_Asignacion
    { 
       get
       {
          return _Hora_Asignacion;
       }
       set
       {
          _Hora_Asignacion = value;
       }
    }
    private string _Hora_Asignacion;

    [RfcField(AbapName = "ESTADO_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 185)]
    [XmlElement("ESTADO_PENDIENTE")]
    public string Estado_Pendiente
    { 
       get
       {
          return _Estado_Pendiente;
       }
       set
       {
          _Estado_Pendiente = value;
       }
    }
    private string _Estado_Pendiente;

    [RfcField(AbapName = "FECHA_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 186)]
    [XmlElement("FECHA_PENDIENTE")]
    public string Fecha_Pendiente
    { 
       get
       {
          return _Fecha_Pendiente;
       }
       set
       {
          _Fecha_Pendiente = value;
       }
    }
    private string _Fecha_Pendiente;

    [RfcField(AbapName = "HORA_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 194)]
    [XmlElement("HORA_PENDIENTE")]
    public string Hora_Pendiente
    { 
       get
       {
          return _Hora_Pendiente;
       }
       set
       {
          _Hora_Pendiente = value;
       }
    }
    private string _Hora_Pendiente;

    [RfcField(AbapName = "USUARIO_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 200)]
    [XmlElement("USUARIO_PENDIENTE")]
    public string Usuario_Pendiente
    { 
       get
       {
          return _Usuario_Pendiente;
       }
       set
       {
          _Usuario_Pendiente = value;
       }
    }
    private string _Usuario_Pendiente;

    [RfcField(AbapName = "NOMUSU_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 210)]
    [XmlElement("NOMUSU_PENDIENTE")]
    public string Nomusu_Pendiente
    { 
       get
       {
          return _Nomusu_Pendiente;
       }
       set
       {
          _Nomusu_Pendiente = value;
       }
    }
    private string _Nomusu_Pendiente;

    [RfcField(AbapName = "ESTADO_ACTIVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 250)]
    [XmlElement("ESTADO_ACTIVACION")]
    public string Estado_Activacion
    { 
       get
       {
          return _Estado_Activacion;
       }
       set
       {
          _Estado_Activacion = value;
       }
    }
    private string _Estado_Activacion;

    [RfcField(AbapName = "FECHA_ACTIVACION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 251)]
    [XmlElement("FECHA_ACTIVACION")]
    public string Fecha_Activacion
    { 
       get
       {
          return _Fecha_Activacion;
       }
       set
       {
          _Fecha_Activacion = value;
       }
    }
    private string _Fecha_Activacion;

    [RfcField(AbapName = "HORA_ACTIVACION", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 259)]
    [XmlElement("HORA_ACTIVACION")]
    public string Hora_Activacion
    { 
       get
       {
          return _Hora_Activacion;
       }
       set
       {
          _Hora_Activacion = value;
       }
    }
    private string _Hora_Activacion;

    [RfcField(AbapName = "USUARIO_ACTIVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 265)]
    [XmlElement("USUARIO_ACTIVACION")]
    public string Usuario_Activacion
    { 
       get
       {
          return _Usuario_Activacion;
       }
       set
       {
          _Usuario_Activacion = value;
       }
    }
    private string _Usuario_Activacion;

    [RfcField(AbapName = "NOMUSU_ACTIVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 275)]
    [XmlElement("NOMUSU_ACTIVACION")]
    public string Nomusu_Activacion
    { 
       get
       {
          return _Nomusu_Activacion;
       }
       set
       {
          _Nomusu_Activacion = value;
       }
    }
    private string _Nomusu_Activacion;

    [RfcField(AbapName = "ESTADO_RECHAZO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 315)]
    [XmlElement("ESTADO_RECHAZO")]
    public string Estado_Rechazo
    { 
       get
       {
          return _Estado_Rechazo;
       }
       set
       {
          _Estado_Rechazo = value;
       }
    }
    private string _Estado_Rechazo;

    [RfcField(AbapName = "FECHA_RECHAZO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 316)]
    [XmlElement("FECHA_RECHAZO")]
    public string Fecha_Rechazo
    { 
       get
       {
          return _Fecha_Rechazo;
       }
       set
       {
          _Fecha_Rechazo = value;
       }
    }
    private string _Fecha_Rechazo;

    [RfcField(AbapName = "HORA_RECHAZO", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 324)]
    [XmlElement("HORA_RECHAZO")]
    public string Hora_Rechazo
    { 
       get
       {
          return _Hora_Rechazo;
       }
       set
       {
          _Hora_Rechazo = value;
       }
    }
    private string _Hora_Rechazo;

    [RfcField(AbapName = "USUARIO_RECHAZO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 330)]
    [XmlElement("USUARIO_RECHAZO")]
    public string Usuario_Rechazo
    { 
       get
       {
          return _Usuario_Rechazo;
       }
       set
       {
          _Usuario_Rechazo = value;
       }
    }
    private string _Usuario_Rechazo;

    [RfcField(AbapName = "NOMUSU_RECHAZO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 340)]
    [XmlElement("NOMUSU_RECHAZO")]
    public string Nomusu_Rechazo
    { 
       get
       {
          return _Nomusu_Rechazo;
       }
       set
       {
          _Nomusu_Rechazo = value;
       }
    }
    private string _Nomusu_Rechazo;

    [RfcField(AbapName = "ESTADO_ANULADOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 380)]
    [XmlElement("ESTADO_ANULADOR")]
    public string Estado_Anulador
    { 
       get
       {
          return _Estado_Anulador;
       }
       set
       {
          _Estado_Anulador = value;
       }
    }
    private string _Estado_Anulador;

    [RfcField(AbapName = "USUARIO_ANULADOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 381)]
    [XmlElement("USUARIO_ANULADOR")]
    public string Usuario_Anulador
    { 
       get
       {
          return _Usuario_Anulador;
       }
       set
       {
          _Usuario_Anulador = value;
       }
    }
    private string _Usuario_Anulador;

    [RfcField(AbapName = "NOMUSU_ANULADOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 391)]
    [XmlElement("NOMUSU_ANULADOR")]
    public string Nomusu_Anulador
    { 
       get
       {
          return _Nomusu_Anulador;
       }
       set
       {
          _Nomusu_Anulador = value;
       }
    }
    private string _Nomusu_Anulador;

    [RfcField(AbapName = "FECHA_ANULADOR", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 431)]
    [XmlElement("FECHA_ANULADOR")]
    public string Fecha_Anulador
    { 
       get
       {
          return _Fecha_Anulador;
       }
       set
       {
          _Fecha_Anulador = value;
       }
    }
    private string _Fecha_Anulador;

    [RfcField(AbapName = "HORA_ANULADOR", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 439)]
    [XmlElement("HORA_ANULADOR")]
    public string Hora_Anulador
    { 
       get
       {
          return _Hora_Anulador;
       }
       set
       {
          _Hora_Anulador = value;
       }
    }
    private string _Hora_Anulador;

    [RfcField(AbapName = "TIPO_DOC_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 445)]
    [XmlElement("TIPO_DOC_CLIENTE")]
    public string Tipo_Doc_Cliente
    { 
       get
       {
          return _Tipo_Doc_Cliente;
       }
       set
       {
          _Tipo_Doc_Cliente = value;
       }
    }
    private string _Tipo_Doc_Cliente;

    [RfcField(AbapName = "COD_BSCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Offset = 447)]
    [XmlElement("COD_BSCS")]
    public string Cod_Bscs
    { 
       get
       {
          return _Cod_Bscs;
       }
       set
       {
          _Cod_Bscs = value;
       }
    }
    private string _Cod_Bscs;

    [RfcField(AbapName = "DES_ESTADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 472)]
    [XmlElement("DES_ESTADO")]
    public string Des_Estado
    { 
       get
       {
          return _Des_Estado;
       }
       set
       {
          _Des_Estado = value;
       }
    }
    private string _Des_Estado;

    [RfcField(AbapName = "IND_EQUIPO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 492)]
    [XmlElement("IND_EQUIPO")]
    public string Ind_Equipo
    { 
       get
       {
          return _Ind_Equipo;
       }
       set
       {
          _Ind_Equipo = value;
       }
    }
    private string _Ind_Equipo;

    [RfcField(AbapName = "FECHA_CONTRATO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 493)]
    [XmlElement("FECHA_CONTRATO")]
    public string Fecha_Contrato
    { 
       get
       {
          return _Fecha_Contrato;
       }
       set
       {
          _Fecha_Contrato = value;
       }
    }
    private string _Fecha_Contrato;

    [RfcField(AbapName = "COD_CLIENTE_SAP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 501)]
    [XmlElement("COD_CLIENTE_SAP")]
    public string Cod_Cliente_Sap
    { 
       get
       {
          return _Cod_Cliente_Sap;
       }
       set
       {
          _Cod_Cliente_Sap = value;
       }
    }
    private string _Cod_Cliente_Sap;

    [RfcField(AbapName = "NRO_TELEFONO_1", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 511)]
    [XmlElement("NRO_TELEFONO_1")]
    public string Nro_Telefono_1
    { 
       get
       {
          return _Nro_Telefono_1;
       }
       set
       {
          _Nro_Telefono_1 = value;
       }
    }
    private string _Nro_Telefono_1;

    [RfcField(AbapName = "COD_PLAN_TARIF_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 526)]
    [XmlElement("COD_PLAN_TARIF_1")]
    public string Cod_Plan_Tarif_1
    { 
       get
       {
          return _Cod_Plan_Tarif_1;
       }
       set
       {
          _Cod_Plan_Tarif_1 = value;
       }
    }
    private string _Cod_Plan_Tarif_1;

    [RfcField(AbapName = "DES_PLAN_TARIF_1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 529)]
    [XmlElement("DES_PLAN_TARIF_1")]
    public string Des_Plan_Tarif_1
    { 
       get
       {
          return _Des_Plan_Tarif_1;
       }
       set
       {
          _Des_Plan_Tarif_1 = value;
       }
    }
    private string _Des_Plan_Tarif_1;

    [RfcField(AbapName = "NRO_TELEFONO_2", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 549)]
    [XmlElement("NRO_TELEFONO_2")]
    public string Nro_Telefono_2
    { 
       get
       {
          return _Nro_Telefono_2;
       }
       set
       {
          _Nro_Telefono_2 = value;
       }
    }
    private string _Nro_Telefono_2;

    [RfcField(AbapName = "COD_PLAN_TARIF_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 564)]
    [XmlElement("COD_PLAN_TARIF_2")]
    public string Cod_Plan_Tarif_2
    { 
       get
       {
          return _Cod_Plan_Tarif_2;
       }
       set
       {
          _Cod_Plan_Tarif_2 = value;
       }
    }
    private string _Cod_Plan_Tarif_2;

    [RfcField(AbapName = "DES_PLAN_TARIF_2", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 567)]
    [XmlElement("DES_PLAN_TARIF_2")]
    public string Des_Plan_Tarif_2
    { 
       get
       {
          return _Des_Plan_Tarif_2;
       }
       set
       {
          _Des_Plan_Tarif_2 = value;
       }
    }
    private string _Des_Plan_Tarif_2;

    [RfcField(AbapName = "NRO_TELEFONO_3", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 587)]
    [XmlElement("NRO_TELEFONO_3")]
    public string Nro_Telefono_3
    { 
       get
       {
          return _Nro_Telefono_3;
       }
       set
       {
          _Nro_Telefono_3 = value;
       }
    }
    private string _Nro_Telefono_3;

    [RfcField(AbapName = "COD_PLAN_TARIF_3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 602)]
    [XmlElement("COD_PLAN_TARIF_3")]
    public string Cod_Plan_Tarif_3
    { 
       get
       {
          return _Cod_Plan_Tarif_3;
       }
       set
       {
          _Cod_Plan_Tarif_3 = value;
       }
    }
    private string _Cod_Plan_Tarif_3;

    [RfcField(AbapName = "DES_PLAN_TARIF_3", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 605)]
    [XmlElement("DES_PLAN_TARIF_3")]
    public string Des_Plan_Tarif_3
    { 
       get
       {
          return _Des_Plan_Tarif_3;
       }
       set
       {
          _Des_Plan_Tarif_3 = value;
       }
    }
    private string _Des_Plan_Tarif_3;

    [RfcField(AbapName = "OBSERVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 625)]
    [XmlElement("OBSERVACION")]
    public string Observacion
    { 
       get
       {
          return _Observacion;
       }
       set
       {
          _Observacion = value;
       }
    }
    private string _Observacion;

    [RfcField(AbapName = "CODIGO_APROBACIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 825)]
    [XmlElement("CODIGO_APROBACIO")]
    public string Codigo_Aprobacio
    { 
       get
       {
          return _Codigo_Aprobacio;
       }
       set
       {
          _Codigo_Aprobacio = value;
       }
    }
    private string _Codigo_Aprobacio;

    [RfcField(AbapName = "NUMERO_HDC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 845)]
    [XmlElement("NUMERO_HDC")]
    public string Numero_Hdc
    { 
       get
       {
          return _Numero_Hdc;
       }
       set
       {
          _Numero_Hdc = value;
       }
    }
    private string _Numero_Hdc;

    [RfcField(AbapName = "PLAN_ANTERIOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 855)]
    [XmlElement("PLAN_ANTERIOR")]
    public string Plan_Anterior
    { 
       get
       {
          return _Plan_Anterior;
       }
       set
       {
          _Plan_Anterior = value;
       }
    }
    private string _Plan_Anterior;

    [RfcField(AbapName = "DEN_PLAN_ANT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 858)]
    [XmlElement("DEN_PLAN_ANT")]
    public string Den_Plan_Ant
    { 
       get
       {
          return _Den_Plan_Ant;
       }
       set
       {
          _Den_Plan_Ant = value;
       }
    }
    private string _Den_Plan_Ant;

    [RfcField(AbapName = "PLAZO_ACUERDO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 878)]
    [XmlElement("PLAZO_ACUERDO")]
    public string Plazo_Acuerdo
    { 
       get
       {
          return _Plazo_Acuerdo;
       }
       set
       {
          _Plazo_Acuerdo = value;
       }
    }
    private string _Plazo_Acuerdo;

    [RfcField(AbapName = "DENOM_PLAZO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 880)]
    [XmlElement("DENOM_PLAZO")]
    public string Denom_Plazo
    { 
       get
       {
          return _Denom_Plazo;
       }
       set
       {
          _Denom_Plazo = value;
       }
    }
    private string _Denom_Plazo;

    [RfcField(AbapName = "TIPO_RENOVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 910)]
    [XmlElement("TIPO_RENOVACION")]
    public string Tipo_Renovacion
    { 
       get
       {
          return _Tipo_Renovacion;
       }
       set
       {
          _Tipo_Renovacion = value;
       }
    }
    private string _Tipo_Renovacion;

    [RfcField(AbapName = "VEND_RENOV", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 925)]
    [XmlElement("VEND_RENOV")]
    public string Vend_Renov
    { 
       get
       {
          return _Vend_Renov;
       }
       set
       {
          _Vend_Renov = value;
       }
    }
    private string _Vend_Renov;

    [RfcField(AbapName = "NOM_VENDEDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 935)]
    [XmlElement("NOM_VENDEDOR")]
    public string Nom_Vendedor
    { 
       get
       {
          return _Nom_Vendedor;
       }
       set
       {
          _Nom_Vendedor = value;
       }
    }
    private string _Nom_Vendedor;

    [RfcField(AbapName = "CLASE_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 975)]
    [XmlElement("CLASE_VENTA")]
    public string Clase_Venta
    { 
       get
       {
          return _Clase_Venta;
       }
       set
       {
          _Clase_Venta = value;
       }
    }
    private string _Clase_Venta;

    [RfcField(AbapName = "DENOM_CLASE_VTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 977)]
    [XmlElement("DENOM_CLASE_VTA")]
    public string Denom_Clase_Vta
    { 
       get
       {
          return _Denom_Clase_Vta;
       }
       set
       {
          _Denom_Clase_Vta = value;
       }
    }
    private string _Denom_Clase_Vta;

    [RfcField(AbapName = "OBS_RECHAZO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 992)]
    [XmlElement("OBS_RECHAZO")]
    public string Obs_Rechazo
    { 
       get
       {
          return _Obs_Rechazo;
       }
       set
       {
          _Obs_Rechazo = value;
       }
    }
    private string _Obs_Rechazo;

    [RfcField(AbapName = "OBS_ANULACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 1192)]
    [XmlElement("OBS_ANULACION")]
    public string Obs_Anulacion
    { 
       get
       {
          return _Obs_Anulacion;
       }
       set
       {
          _Obs_Anulacion = value;
       }
    }
    private string _Obs_Anulacion;

    [RfcField(AbapName = "OBS_PENDIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 1392)]
    [XmlElement("OBS_PENDIENTE")]
    public string Obs_Pendiente
    { 
       get
       {
          return _Obs_Pendiente;
       }
       set
       {
          _Obs_Pendiente = value;
       }
    }
    private string _Obs_Pendiente;

    [RfcField(AbapName = "TIPO_ACTIV_CLTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 1592)]
    [XmlElement("TIPO_ACTIV_CLTE")]
    public string Tipo_Activ_Clte
    { 
       get
       {
          return _Tipo_Activ_Clte;
       }
       set
       {
          _Tipo_Activ_Clte = value;
       }
    }
    private string _Tipo_Activ_Clte;

    [RfcField(AbapName = "ACTIVACION_LINEA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 1593)]
    [XmlElement("ACTIVACION_LINEA")]
    public string Activacion_Linea
    { 
       get
       {
          return _Activacion_Linea;
       }
       set
       {
          _Activacion_Linea = value;
       }
    }
    private string _Activacion_Linea;

    [RfcField(AbapName = "SERV_BLACKBERRY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 1594)]
    [XmlElement("SERV_BLACKBERRY")]
    public string Serv_Blackberry
    { 
       get
       {
          return _Serv_Blackberry;
       }
       set
       {
          _Serv_Blackberry = value;
       }
    }
    private string _Serv_Blackberry;

    [RfcField(AbapName = "MOTIVO_MIG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 1595)]
    [XmlElement("MOTIVO_MIG")]
    public string Motivo_Mig
    { 
       get
       {
          return _Motivo_Mig;
       }
       set
       {
          _Motivo_Mig = value;
       }
    }
    private string _Motivo_Mig;

  }

}
