
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_CONTRATO" , Length = 814)]
  public class ZST_PV_CONTRATO : SAPStructure
  {
    
    [RfcField(AbapName = "NUMERO_CONTRATO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("NUMERO_CONTRATO")]
    public string Numero_Contrato
    { 
       get
       {
          return _Numero_Contrato;
       }
       set
       {
          _Numero_Contrato = value;
       }
    }
    private string _Numero_Contrato;

    [RfcField(AbapName = "OFICINA_VENTAS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 10)]
    [XmlElement("OFICINA_VENTAS")]
    public string Oficina_Ventas
    { 
       get
       {
          return _Oficina_Ventas;
       }
       set
       {
          _Oficina_Ventas = value;
       }
    }
    private string _Oficina_Ventas;

    [RfcField(AbapName = "NUMERO_PCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 14)]
    [XmlElement("NUMERO_PCS")]
    public string Numero_Pcs
    { 
       get
       {
          return _Numero_Pcs;
       }
       set
       {
          _Numero_Pcs = value;
       }
    }
    private string _Numero_Pcs;

    [RfcField(AbapName = "FECHA_CONTRATO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 44)]
    [XmlElement("FECHA_CONTRATO")]
    public string Fecha_Contrato
    { 
       get
       {
          return _Fecha_Contrato;
       }
       set
       {
          _Fecha_Contrato = value;
       }
    }
    private string _Fecha_Contrato;

    [RfcField(AbapName = "PLAZO_ACUERDO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 52)]
    [XmlElement("PLAZO_ACUERDO")]
    public string Plazo_Acuerdo
    { 
       get
       {
          return _Plazo_Acuerdo;
       }
       set
       {
          _Plazo_Acuerdo = value;
       }
    }
    private string _Plazo_Acuerdo;

    [RfcField(AbapName = "FACT_NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 54)]
    [XmlElement("FACT_NOMBRE")]
    public string Fact_Nombre
    { 
       get
       {
          return _Fact_Nombre;
       }
       set
       {
          _Fact_Nombre = value;
       }
    }
    private string _Fact_Nombre;

    [RfcField(AbapName = "FACT_APEL_PAT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 94)]
    [XmlElement("FACT_APEL_PAT")]
    public string Fact_Apel_Pat
    { 
       get
       {
          return _Fact_Apel_Pat;
       }
       set
       {
          _Fact_Apel_Pat = value;
       }
    }
    private string _Fact_Apel_Pat;

    [RfcField(AbapName = "FACT_APE_MAT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 114)]
    [XmlElement("FACT_APE_MAT")]
    public string Fact_Ape_Mat
    { 
       get
       {
          return _Fact_Ape_Mat;
       }
       set
       {
          _Fact_Ape_Mat = value;
       }
    }
    private string _Fact_Ape_Mat;

    [RfcField(AbapName = "FACT_R_SOCIAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 134)]
    [XmlElement("FACT_R_SOCIAL")]
    public string Fact_R_Social
    { 
       get
       {
          return _Fact_R_Social;
       }
       set
       {
          _Fact_R_Social = value;
       }
    }
    private string _Fact_R_Social;

    [RfcField(AbapName = "CODIGO_APROBACIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 174)]
    [XmlElement("CODIGO_APROBACIO")]
    public string Codigo_Aprobacio
    { 
       get
       {
          return _Codigo_Aprobacio;
       }
       set
       {
          _Codigo_Aprobacio = value;
       }
    }
    private string _Codigo_Aprobacio;

    [RfcField(AbapName = "RESULTADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 194)]
    [XmlElement("RESULTADO")]
    public string Resultado
    { 
       get
       {
          return _Resultado;
       }
       set
       {
          _Resultado = value;
       }
    }
    private string _Resultado;

    [RfcField(AbapName = "IMPRESO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 234)]
    [XmlElement("IMPRESO")]
    public string Impreso
    { 
       get
       {
          return _Impreso;
       }
       set
       {
          _Impreso = value;
       }
    }
    private string _Impreso;

    [RfcField(AbapName = "FECHA_REGISTRO", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 235)]
    [XmlElement("FECHA_REGISTRO")]
    public string Fecha_Registro
    { 
       get
       {
          return _Fecha_Registro;
       }
       set
       {
          _Fecha_Registro = value;
       }
    }
    private string _Fecha_Registro;

    [RfcField(AbapName = "FECHA_ACTUALIZ", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 243)]
    [XmlElement("FECHA_ACTUALIZ")]
    public string Fecha_Actualiz
    { 
       get
       {
          return _Fecha_Actualiz;
       }
       set
       {
          _Fecha_Actualiz = value;
       }
    }
    private string _Fecha_Actualiz;

    [RfcField(AbapName = "DOC_SUSTENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 251)]
    [XmlElement("DOC_SUSTENTO")]
    public string Doc_Sustento
    { 
       get
       {
          return _Doc_Sustento;
       }
       set
       {
          _Doc_Sustento = value;
       }
    }
    private string _Doc_Sustento;

    [RfcField(AbapName = "TARJETA_CREDITO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 253)]
    [XmlElement("TARJETA_CREDITO")]
    public string Tarjeta_Credito
    { 
       get
       {
          return _Tarjeta_Credito;
       }
       set
       {
          _Tarjeta_Credito = value;
       }
    }
    private string _Tarjeta_Credito;

    [RfcField(AbapName = "NUM_TARJ_CREDITO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 257)]
    [XmlElement("NUM_TARJ_CREDITO")]
    public string Num_Tarj_Credito
    { 
       get
       {
          return _Num_Tarj_Credito;
       }
       set
       {
          _Num_Tarj_Credito = value;
       }
    }
    private string _Num_Tarj_Credito;

    [RfcField(AbapName = "MONEDA_TCRED", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 277)]
    [XmlElement("MONEDA_TCRED")]
    public string Moneda_Tcred
    { 
       get
       {
          return _Moneda_Tcred;
       }
       set
       {
          _Moneda_Tcred = value;
       }
    }
    private string _Moneda_Tcred;

    [RfcField(AbapName = "LINEA_CREDITO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 278)]
    [XmlElement("LINEA_CREDITO")]
    public Decimal Linea_Credito
    { 
       get
       {
          return _Linea_Credito;
       }
       set
       {
          _Linea_Credito = value;
       }
    }
    private Decimal _Linea_Credito;

    [RfcField(AbapName = "FECHA_VENC_TCRED", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 8, Offset = 286)]
    [XmlElement("FECHA_VENC_TCRED")]
    public string Fecha_Venc_Tcred
    { 
       get
       {
          return _Fecha_Venc_Tcred;
       }
       set
       {
          _Fecha_Venc_Tcred = value;
       }
    }
    private string _Fecha_Venc_Tcred;

    [RfcField(AbapName = "VENDEDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 294)]
    [XmlElement("VENDEDOR")]
    public string Vendedor
    { 
       get
       {
          return _Vendedor;
       }
       set
       {
          _Vendedor = value;
       }
    }
    private string _Vendedor;

    [RfcField(AbapName = "TELEFONO_VENDEDO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 304)]
    [XmlElement("TELEFONO_VENDEDO")]
    public string Telefono_Vendedo
    { 
       get
       {
          return _Telefono_Vendedo;
       }
       set
       {
          _Telefono_Vendedo = value;
       }
    }
    private string _Telefono_Vendedo;

    [RfcField(AbapName = "DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 319)]
    [XmlElement("DOCUMENTO")]
    public string Documento
    { 
       get
       {
          return _Documento;
       }
       set
       {
          _Documento = value;
       }
    }
    private string _Documento;

    [RfcField(AbapName = "VIA_PAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 329)]
    [XmlElement("VIA_PAGO")]
    public string Via_Pago
    { 
       get
       {
          return _Via_Pago;
       }
       set
       {
          _Via_Pago = value;
       }
    }
    private string _Via_Pago;

    [RfcField(AbapName = "DEBITO_AUTOMATI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 333)]
    [XmlElement("DEBITO_AUTOMATI")]
    public string Debito_Automati
    { 
       get
       {
          return _Debito_Automati;
       }
       set
       {
          _Debito_Automati = value;
       }
    }
    private string _Debito_Automati;

    [RfcField(AbapName = "ANALISTA_CREDITO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 334)]
    [XmlElement("ANALISTA_CREDITO")]
    public string Analista_Credito
    { 
       get
       {
          return _Analista_Credito;
       }
       set
       {
          _Analista_Credito = value;
       }
    }
    private string _Analista_Credito;

    [RfcField(AbapName = "MIGRACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 338)]
    [XmlElement("MIGRACION")]
    public string Migracion
    { 
       get
       {
          return _Migracion;
       }
       set
       {
          _Migracion = value;
       }
    }
    private string _Migracion;

    [RfcField(AbapName = "ESTADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 339)]
    [XmlElement("ESTADO")]
    public string Estado
    { 
       get
       {
          return _Estado;
       }
       set
       {
          _Estado = value;
       }
    }
    private string _Estado;

    [RfcField(AbapName = "COD_OBSERVACION", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 340)]
    [XmlElement("COD_OBSERVACION")]
    public string Cod_Observacion
    { 
       get
       {
          return _Cod_Observacion;
       }
       set
       {
          _Cod_Observacion = value;
       }
    }
    private string _Cod_Observacion;

    [RfcField(AbapName = "OBSERVACIONES", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 343)]
    [XmlElement("OBSERVACIONES")]
    public string Observaciones
    { 
       get
       {
          return _Observaciones;
       }
       set
       {
          _Observaciones = value;
       }
    }
    private string _Observaciones;

    [RfcField(AbapName = "TIPO_RECHAZO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 543)]
    [XmlElement("TIPO_RECHAZO")]
    public string Tipo_Rechazo
    { 
       get
       {
          return _Tipo_Rechazo;
       }
       set
       {
          _Tipo_Rechazo = value;
       }
    }
    private string _Tipo_Rechazo;

    [RfcField(AbapName = "VIA_DSF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 546)]
    [XmlElement("VIA_DSF")]
    public string Via_Dsf
    { 
       get
       {
          return _Via_Dsf;
       }
       set
       {
          _Via_Dsf = value;
       }
    }
    private string _Via_Dsf;

    [RfcField(AbapName = "TIPO_DOC_CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 547)]
    [XmlElement("TIPO_DOC_CLIENTE")]
    public string Tipo_Doc_Cliente
    { 
       get
       {
          return _Tipo_Doc_Cliente;
       }
       set
       {
          _Tipo_Doc_Cliente = value;
       }
    }
    private string _Tipo_Doc_Cliente;

    [RfcField(AbapName = "CLIENTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 549)]
    [XmlElement("CLIENTE")]
    public string Cliente
    { 
       get
       {
          return _Cliente;
       }
       set
       {
          _Cliente = value;
       }
    }
    private string _Cliente;

    [RfcField(AbapName = "TELEF_RENOV", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 565)]
    [XmlElement("TELEF_RENOV")]
    public string Telef_Renov
    { 
       get
       {
          return _Telef_Renov;
       }
       set
       {
          _Telef_Renov = value;
       }
    }
    private string _Telef_Renov;

    [RfcField(AbapName = "PLAN_RENOV", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 580)]
    [XmlElement("PLAN_RENOV")]
    public string Plan_Renov
    { 
       get
       {
          return _Plan_Renov;
       }
       set
       {
          _Plan_Renov = value;
       }
    }
    private string _Plan_Renov;

    [RfcField(AbapName = "RENOVACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 583)]
    [XmlElement("RENOVACION")]
    public string Renovacion
    { 
       get
       {
          return _Renovacion;
       }
       set
       {
          _Renovacion = value;
       }
    }
    private string _Renovacion;

    [RfcField(AbapName = "CODIGO_BANCO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 584)]
    [XmlElement("CODIGO_BANCO")]
    public string Codigo_Banco
    { 
       get
       {
          return _Codigo_Banco;
       }
       set
       {
          _Codigo_Banco = value;
       }
    }
    private string _Codigo_Banco;

    [RfcField(AbapName = "NRO_CLARIFY", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 599)]
    [XmlElement("NRO_CLARIFY")]
    public string Nro_Clarify
    { 
       get
       {
          return _Nro_Clarify;
       }
       set
       {
          _Nro_Clarify = value;
       }
    }
    private string _Nro_Clarify;

    [RfcField(AbapName = "NUMERO_HDC", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 609)]
    [XmlElement("NUMERO_HDC")]
    public string Numero_Hdc
    { 
       get
       {
          return _Numero_Hdc;
       }
       set
       {
          _Numero_Hdc = value;
       }
    }
    private string _Numero_Hdc;

    [RfcField(AbapName = "REPOSICION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 619)]
    [XmlElement("REPOSICION")]
    public string Reposicion
    { 
       get
       {
          return _Reposicion;
       }
       set
       {
          _Reposicion = value;
       }
    }
    private string _Reposicion;

    [RfcField(AbapName = "CAMPANA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 620)]
    [XmlElement("CAMPANA")]
    public string Campana
    { 
       get
       {
          return _Campana;
       }
       set
       {
          _Campana = value;
       }
    }
    private string _Campana;

    [RfcField(AbapName = "APROBADOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 624)]
    [XmlElement("APROBADOR")]
    public string Aprobador
    { 
       get
       {
          return _Aprobador;
       }
       set
       {
          _Aprobador = value;
       }
    }
    private string _Aprobador;

    [RfcField(AbapName = "LIM_CREDITO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 627)]
    [XmlElement("LIM_CREDITO")]
    public Decimal Lim_Credito
    { 
       get
       {
          return _Lim_Credito;
       }
       set
       {
          _Lim_Credito = value;
       }
    }
    private Decimal _Lim_Credito;

    [RfcField(AbapName = "EVAL_CRED_MANUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 635)]
    [XmlElement("EVAL_CRED_MANUAL")]
    public string Eval_Cred_Manual
    { 
       get
       {
          return _Eval_Cred_Manual;
       }
       set
       {
          _Eval_Cred_Manual = value;
       }
    }
    private string _Eval_Cred_Manual;

    [RfcField(AbapName = "SCORE_CREDITICIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 636)]
    [XmlElement("SCORE_CREDITICIO")]
    public string Score_Crediticio
    { 
       get
       {
          return _Score_Crediticio;
       }
       set
       {
          _Score_Crediticio = value;
       }
    }
    private string _Score_Crediticio;

    [RfcField(AbapName = "CONTROL_FRAUDE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 638)]
    [XmlElement("CONTROL_FRAUDE")]
    public string Control_Fraude
    { 
       get
       {
          return _Control_Fraude;
       }
       set
       {
          _Control_Fraude = value;
       }
    }
    private string _Control_Fraude;

    [RfcField(AbapName = "NRO_CARPETA_OBS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 642)]
    [XmlElement("NRO_CARPETA_OBS")]
    public string Nro_Carpeta_Obs
    { 
       get
       {
          return _Nro_Carpeta_Obs;
       }
       set
       {
          _Nro_Carpeta_Obs = value;
       }
    }
    private string _Nro_Carpeta_Obs;

    [RfcField(AbapName = "NRO_CONTRATO_ANT", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 652)]
    [XmlElement("NRO_CONTRATO_ANT")]
    public string Nro_Contrato_Ant
    { 
       get
       {
          return _Nro_Contrato_Ant;
       }
       set
       {
          _Nro_Contrato_Ant = value;
       }
    }
    private string _Nro_Contrato_Ant;

    [RfcField(AbapName = "OPERADOR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 662)]
    [XmlElement("OPERADOR")]
    public string Operador
    { 
       get
       {
          return _Operador;
       }
       set
       {
          _Operador = value;
       }
    }
    private string _Operador;

    [RfcField(AbapName = "PLAN_ANTERIOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 664)]
    [XmlElement("PLAN_ANTERIOR")]
    public string Plan_Anterior
    { 
       get
       {
          return _Plan_Anterior;
       }
       set
       {
          _Plan_Anterior = value;
       }
    }
    private string _Plan_Anterior;

    [RfcField(AbapName = "NRO_OPE_INFOCORP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 667)]
    [XmlElement("NRO_OPE_INFOCORP")]
    public string Nro_Ope_Infocorp
    { 
       get
       {
          return _Nro_Ope_Infocorp;
       }
       set
       {
          _Nro_Ope_Infocorp = value;
       }
    }
    private string _Nro_Ope_Infocorp;

    [RfcField(AbapName = "CS_LARGE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 19, Offset = 687)]
    [XmlElement("CS_LARGE")]
    public string Cs_Large
    { 
       get
       {
          return _Cs_Large;
       }
       set
       {
          _Cs_Large = value;
       }
    }
    private string _Cs_Large;

    [RfcField(AbapName = "CS_SUBCUENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 19, Offset = 706)]
    [XmlElement("CS_SUBCUENTA")]
    public string Cs_Subcuenta
    { 
       get
       {
          return _Cs_Subcuenta;
       }
       set
       {
          _Cs_Subcuenta = value;
       }
    }
    private string _Cs_Subcuenta;

    [RfcField(AbapName = "LIM_CRED_MAX", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 725)]
    [XmlElement("LIM_CRED_MAX")]
    public Decimal Lim_Cred_Max
    { 
       get
       {
          return _Lim_Cred_Max;
       }
       set
       {
          _Lim_Cred_Max = value;
       }
    }
    private Decimal _Lim_Cred_Max;

    [RfcField(AbapName = "SUM_PLANES_ACTUA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 733)]
    [XmlElement("SUM_PLANES_ACTUA")]
    public Decimal Sum_Planes_Actua
    { 
       get
       {
          return _Sum_Planes_Actua;
       }
       set
       {
          _Sum_Planes_Actua = value;
       }
    }
    private Decimal _Sum_Planes_Actua;

    [RfcField(AbapName = "SUM_PLANES_VENDI", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 741)]
    [XmlElement("SUM_PLANES_VENDI")]
    public Decimal Sum_Planes_Vendi
    { 
       get
       {
          return _Sum_Planes_Vendi;
       }
       set
       {
          _Sum_Planes_Vendi = value;
       }
    }
    private Decimal _Sum_Planes_Vendi;

    [RfcField(AbapName = "RESPONS_PAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 749)]
    [XmlElement("RESPONS_PAGO")]
    public string Respons_Pago
    { 
       get
       {
          return _Respons_Pago;
       }
       set
       {
          _Respons_Pago = value;
       }
    }
    private string _Respons_Pago;

    [RfcField(AbapName = "EXISTE_BSCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 750)]
    [XmlElement("EXISTE_BSCS")]
    public string Existe_Bscs
    { 
       get
       {
          return _Existe_Bscs;
       }
       set
       {
          _Existe_Bscs = value;
       }
    }
    private string _Existe_Bscs;

    [RfcField(AbapName = "TIPO_ACTIV_CLTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 751)]
    [XmlElement("TIPO_ACTIV_CLTE")]
    public string Tipo_Activ_Clte
    { 
       get
       {
          return _Tipo_Activ_Clte;
       }
       set
       {
          _Tipo_Activ_Clte = value;
       }
    }
    private string _Tipo_Activ_Clte;

    [RfcField(AbapName = "ACTIVACION_LINEA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 752)]
    [XmlElement("ACTIVACION_LINEA")]
    public string Activacion_Linea
    { 
       get
       {
          return _Activacion_Linea;
       }
       set
       {
          _Activacion_Linea = value;
       }
    }
    private string _Activacion_Linea;

    [RfcField(AbapName = "ACUERDO_MANUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 753)]
    [XmlElement("ACUERDO_MANUAL")]
    public string Acuerdo_Manual
    { 
       get
       {
          return _Acuerdo_Manual;
       }
       set
       {
          _Acuerdo_Manual = value;
       }
    }
    private string _Acuerdo_Manual;

    [RfcField(AbapName = "TIPO_CLI_ACT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 754)]
    [XmlElement("TIPO_CLI_ACT")]
    public string Tipo_Cli_Act
    { 
       get
       {
          return _Tipo_Cli_Act;
       }
       set
       {
          _Tipo_Cli_Act = value;
       }
    }
    private string _Tipo_Cli_Act;

    [RfcField(AbapName = "TIPO_VTA_ORI", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 756)]
    [XmlElement("TIPO_VTA_ORI")]
    public string Tipo_Vta_Ori
    { 
       get
       {
          return _Tipo_Vta_Ori;
       }
       set
       {
          _Tipo_Vta_Ori = value;
       }
    }
    private string _Tipo_Vta_Ori;

    [RfcField(AbapName = "MOTIVO_MIG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 758)]
    [XmlElement("MOTIVO_MIG")]
    public string Motivo_Mig
    { 
       get
       {
          return _Motivo_Mig;
       }
       set
       {
          _Motivo_Mig = value;
       }
    }
    private string _Motivo_Mig;

    [RfcField(AbapName = "CON_SIN_EQ", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 50, Offset = 761)]
    [XmlElement("CON_SIN_EQ")]
    public string Con_Sin_Eq
    { 
       get
       {
          return _Con_Sin_Eq;
       }
       set
       {
          _Con_Sin_Eq = value;
       }
    }
    private string _Con_Sin_Eq;

    [RfcField(AbapName = "MOTIVO_REPOS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 811)]
    [XmlElement("MOTIVO_REPOS")]
    public string Motivo_Repos
    { 
       get
       {
          return _Motivo_Repos;
       }
       set
       {
          _Motivo_Repos = value;
       }
    }
    private string _Motivo_Repos;

  }

}
