
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_SERVICIOS_ACUERDO" , Length = 70)]
  public class ZST_PV_SERVICIOS_ACUERDO : SAPStructure
  {
    
    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 0)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;

    [RfcField(AbapName = "SERVICIO_SOLICIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 6)]
    [XmlElement("SERVICIO_SOLICIT")]
    public string Servicio_Solicit
    { 
       get
       {
          return _Servicio_Solicit;
       }
       set
       {
          _Servicio_Solicit = value;
       }
    }
    private string _Servicio_Solicit;

    [RfcField(AbapName = "DESCRIPCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 10)]
    [XmlElement("DESCRIPCION")]
    public string Descripcion
    { 
       get
       {
          return _Descripcion;
       }
       set
       {
          _Descripcion = value;
       }
    }
    private string _Descripcion;

    [RfcField(AbapName = "VALOR_SELECCIONA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 50)]
    [XmlElement("VALOR_SELECCIONA")]
    public string Valor_Selecciona
    { 
       get
       {
          return _Valor_Selecciona;
       }
       set
       {
          _Valor_Selecciona = value;
       }
    }
    private string _Valor_Selecciona;

    [RfcField(AbapName = "ORDEN", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Offset = 51)]
    [XmlElement("ORDEN")]
    public string Orden
    { 
       get
       {
          return _Orden;
       }
       set
       {
          _Orden = value;
       }
    }
    private string _Orden;

    [RfcField(AbapName = "TIPO_MONTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 55)]
    [XmlElement("TIPO_MONTO")]
    public string Tipo_Monto
    { 
       get
       {
          return _Tipo_Monto;
       }
       set
       {
          _Tipo_Monto = value;
       }
    }
    private string _Tipo_Monto;

    [RfcField(AbapName = "MONTO_A_PAGAR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 56)]
    [XmlElement("MONTO_A_PAGAR")]
    public Decimal Monto_A_Pagar
    { 
       get
       {
          return _Monto_A_Pagar;
       }
       set
       {
          _Monto_A_Pagar = value;
       }
    }
    private Decimal _Monto_A_Pagar;

    [RfcField(AbapName = "PERIODO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Offset = 64)]
    [XmlElement("PERIODO")]
    public string Periodo
    { 
       get
       {
          return _Periodo;
       }
       set
       {
          _Periodo = value;
       }
    }
    private string _Periodo;

  }

}
