
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_BSCS_JER" , Length = 108)]
  public class ZST_BSCS_JER : SAPStructure
  {
    
    [RfcField(AbapName = "CS_ID", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 19, Offset = 0)]
    [XmlElement("CS_ID")]
    public string Cs_Id
    { 
       get
       {
          return _Cs_Id;
       }
       set
       {
          _Cs_Id = value;
       }
    }
    private string _Cs_Id;

    [RfcField(AbapName = "CODIGO_BSCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 25, Offset = 19)]
    [XmlElement("CODIGO_BSCS")]
    public string Codigo_Bscs
    { 
       get
       {
          return _Codigo_Bscs;
       }
       set
       {
          _Codigo_Bscs = value;
       }
    }
    private string _Codigo_Bscs;

    [RfcField(AbapName = "CS_ID_HIGH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 19, Offset = 44)]
    [XmlElement("CS_ID_HIGH")]
    public string Cs_Id_High
    { 
       get
       {
          return _Cs_Id_High;
       }
       set
       {
          _Cs_Id_High = value;
       }
    }
    private string _Cs_Id_High;

    [RfcField(AbapName = "CS_LEVEL_CODE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 63)]
    [XmlElement("CS_LEVEL_CODE")]
    public string Cs_Level_Code
    { 
       get
       {
          return _Cs_Level_Code;
       }
       set
       {
          _Cs_Level_Code = value;
       }
    }
    private string _Cs_Level_Code;

    [RfcField(AbapName = "NOMBRE_TITULAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 66)]
    [XmlElement("NOMBRE_TITULAR")]
    public string Nombre_Titular
    { 
       get
       {
          return _Nombre_Titular;
       }
       set
       {
          _Nombre_Titular = value;
       }
    }
    private string _Nombre_Titular;

    [RfcField(AbapName = "TIPO_CLI_ACT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 106)]
    [XmlElement("TIPO_CLI_ACT")]
    public string Tipo_Cli_Act
    { 
       get
       {
          return _Tipo_Cli_Act;
       }
       set
       {
          _Tipo_Cli_Act = value;
       }
    }
    private string _Tipo_Cli_Act;

  }

}
