
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_PARAM_OF_VTA" , Length = 315)]
  public class ZST_PV_PARAM_OF_VTA : SAPStructure
  {
    
    [RfcField(AbapName = "BUKRS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 0)]
    [XmlElement("BUKRS")]
    public string Bukrs
    { 
       get
       {
          return _Bukrs;
       }
       set
       {
          _Bukrs = value;
       }
    }
    private string _Bukrs;

    [RfcField(AbapName = "VKORG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 4)]
    [XmlElement("VKORG")]
    public string Vkorg
    { 
       get
       {
          return _Vkorg;
       }
       set
       {
          _Vkorg = value;
       }
    }
    private string _Vkorg;

    [RfcField(AbapName = "VTWEG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 8)]
    [XmlElement("VTWEG")]
    public string Vtweg
    { 
       get
       {
          return _Vtweg;
       }
       set
       {
          _Vtweg = value;
       }
    }
    private string _Vtweg;

    [RfcField(AbapName = "VKBUR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 10)]
    [XmlElement("VKBUR")]
    public string Vkbur
    { 
       get
       {
          return _Vkbur;
       }
       set
       {
          _Vkbur = value;
       }
    }
    private string _Vkbur;

    [RfcField(AbapName = "SPART", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 14)]
    [XmlElement("SPART")]
    public string Spart
    { 
       get
       {
          return _Spart;
       }
       set
       {
          _Spart = value;
       }
    }
    private string _Spart;

    [RfcField(AbapName = "BEZEI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 16)]
    [XmlElement("BEZEI")]
    public string Bezei
    { 
       get
       {
          return _Bezei;
       }
       set
       {
          _Bezei = value;
       }
    }
    private string _Bezei;

    [RfcField(AbapName = "VTEXT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 36)]
    [XmlElement("VTEXT")]
    public string Vtext
    { 
       get
       {
          return _Vtext;
       }
       set
       {
          _Vtext = value;
       }
    }
    private string _Vtext;

    [RfcField(AbapName = "PROP_TIM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 56)]
    [XmlElement("PROP_TIM")]
    public string Prop_Tim
    { 
       get
       {
          return _Prop_Tim;
       }
       set
       {
          _Prop_Tim = value;
       }
    }
    private string _Prop_Tim;

    [RfcField(AbapName = "VKGRP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 57)]
    [XmlElement("VKGRP")]
    public string Vkgrp
    { 
       get
       {
          return _Vkgrp;
       }
       set
       {
          _Vkgrp = value;
       }
    }
    private string _Vkgrp;

    [RfcField(AbapName = "KTOKD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 60)]
    [XmlElement("KTOKD")]
    public string Ktokd
    { 
       get
       {
          return _Ktokd;
       }
       set
       {
          _Ktokd = value;
       }
    }
    private string _Ktokd;

    [RfcField(AbapName = "BZIRK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Offset = 64)]
    [XmlElement("BZIRK")]
    public string Bzirk
    { 
       get
       {
          return _Bzirk;
       }
       set
       {
          _Bzirk = value;
       }
    }
    private string _Bzirk;

    [RfcField(AbapName = "KDGRP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 70)]
    [XmlElement("KDGRP")]
    public string Kdgrp
    { 
       get
       {
          return _Kdgrp;
       }
       set
       {
          _Kdgrp = value;
       }
    }
    private string _Kdgrp;

    [RfcField(AbapName = "KLABC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 72)]
    [XmlElement("KLABC")]
    public string Klabc
    { 
       get
       {
          return _Klabc;
       }
       set
       {
          _Klabc = value;
       }
    }
    private string _Klabc;

    [RfcField(AbapName = "WAERS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Offset = 74)]
    [XmlElement("WAERS")]
    public string Waers
    { 
       get
       {
          return _Waers;
       }
       set
       {
          _Waers = value;
       }
    }
    private string _Waers;

    [RfcField(AbapName = "KALKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 79)]
    [XmlElement("KALKS")]
    public string Kalks
    { 
       get
       {
          return _Kalks;
       }
       set
       {
          _Kalks = value;
       }
    }
    private string _Kalks;

    [RfcField(AbapName = "VERSG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 80)]
    [XmlElement("VERSG")]
    public string Versg
    { 
       get
       {
          return _Versg;
       }
       set
       {
          _Versg = value;
       }
    }
    private string _Versg;

    [RfcField(AbapName = "VSBED", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 81)]
    [XmlElement("VSBED")]
    public string Vsbed
    { 
       get
       {
          return _Vsbed;
       }
       set
       {
          _Vsbed = value;
       }
    }
    private string _Vsbed;

    [RfcField(AbapName = "ANTLF", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 1, Offset = 83)]
    [XmlElement("ANTLF")]
    public Decimal Antlf
    { 
       get
       {
          return _Antlf;
       }
       set
       {
          _Antlf = value;
       }
    }
    private Decimal _Antlf;

    [RfcField(AbapName = "ZTERM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 84)]
    [XmlElement("ZTERM")]
    public string Zterm
    { 
       get
       {
          return _Zterm;
       }
       set
       {
          _Zterm = value;
       }
    }
    private string _Zterm;

    [RfcField(AbapName = "TAXKD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 88)]
    [XmlElement("TAXKD")]
    public string Taxkd
    { 
       get
       {
          return _Taxkd;
       }
       set
       {
          _Taxkd = value;
       }
    }
    private string _Taxkd;

    [RfcField(AbapName = "BRSCH", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 89)]
    [XmlElement("BRSCH")]
    public string Brsch
    { 
       get
       {
          return _Brsch;
       }
       set
       {
          _Brsch = value;
       }
    }
    private string _Brsch;

    [RfcField(AbapName = "KUKLA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 93)]
    [XmlElement("KUKLA")]
    public string Kukla
    { 
       get
       {
          return _Kukla;
       }
       set
       {
          _Kukla = value;
       }
    }
    private string _Kukla;

    [RfcField(AbapName = "AKONT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 95)]
    [XmlElement("AKONT")]
    public string Akont
    { 
       get
       {
          return _Akont;
       }
       set
       {
          _Akont = value;
       }
    }
    private string _Akont;

    [RfcField(AbapName = "FDGRV", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 105)]
    [XmlElement("FDGRV")]
    public string Fdgrv
    { 
       get
       {
          return _Fdgrv;
       }
       set
       {
          _Fdgrv = value;
       }
    }
    private string _Fdgrv;

    [RfcField(AbapName = "XZVER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 115)]
    [XmlElement("XZVER")]
    public string Xzver
    { 
       get
       {
          return _Xzver;
       }
       set
       {
          _Xzver = value;
       }
    }
    private string _Xzver;

    [RfcField(AbapName = "WERKS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 116)]
    [XmlElement("WERKS")]
    public string Werks
    { 
       get
       {
          return _Werks;
       }
       set
       {
          _Werks = value;
       }
    }
    private string _Werks;

    [RfcField(AbapName = "LGORT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 120)]
    [XmlElement("LGORT")]
    public string Lgort
    { 
       get
       {
          return _Lgort;
       }
       set
       {
          _Lgort = value;
       }
    }
    private string _Lgort;

    [RfcField(AbapName = "VSTEL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 124)]
    [XmlElement("VSTEL")]
    public string Vstel
    { 
       get
       {
          return _Vstel;
       }
       set
       {
          _Vstel = value;
       }
    }
    private string _Vstel;

    [RfcField(AbapName = "PORC_DCTO_DEALER", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Decimals = 2, Offset = 128)]
    [XmlElement("PORC_DCTO_DEALER")]
    public Decimal Porc_Dcto_Dealer
    { 
       get
       {
          return _Porc_Dcto_Dealer;
       }
       set
       {
          _Porc_Dcto_Dealer = value;
       }
    }
    private Decimal _Porc_Dcto_Dealer;

    [RfcField(AbapName = "IGV_IMPRESION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 132)]
    [XmlElement("IGV_IMPRESION")]
    public string Igv_Impresion
    { 
       get
       {
          return _Igv_Impresion;
       }
       set
       {
          _Igv_Impresion = value;
       }
    }
    private string _Igv_Impresion;

    [RfcField(AbapName = "IGV_VISUALIZA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 133)]
    [XmlElement("IGV_VISUALIZA")]
    public string Igv_Visualiza
    { 
       get
       {
          return _Igv_Visualiza;
       }
       set
       {
          _Igv_Visualiza = value;
       }
    }
    private string _Igv_Visualiza;

    [RfcField(AbapName = "NUM_DOC_BOLETA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 134)]
    [XmlElement("NUM_DOC_BOLETA")]
    public string Num_Doc_Boleta
    { 
       get
       {
          return _Num_Doc_Boleta;
       }
       set
       {
          _Num_Doc_Boleta = value;
       }
    }
    private string _Num_Doc_Boleta;

    [RfcField(AbapName = "NUM_DOC_FACTURA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 135)]
    [XmlElement("NUM_DOC_FACTURA")]
    public string Num_Doc_Factura
    { 
       get
       {
          return _Num_Doc_Factura;
       }
       set
       {
          _Num_Doc_Factura = value;
       }
    }
    private string _Num_Doc_Factura;

    [RfcField(AbapName = "NUM_DOC_NCDTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 136)]
    [XmlElement("NUM_DOC_NCDTO")]
    public string Num_Doc_Ncdto
    { 
       get
       {
          return _Num_Doc_Ncdto;
       }
       set
       {
          _Num_Doc_Ncdto = value;
       }
    }
    private string _Num_Doc_Ncdto;

    [RfcField(AbapName = "NUM_DOC_NDBTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 137)]
    [XmlElement("NUM_DOC_NDBTO")]
    public string Num_Doc_Ndbto
    { 
       get
       {
          return _Num_Doc_Ndbto;
       }
       set
       {
          _Num_Doc_Ndbto = value;
       }
    }
    private string _Num_Doc_Ndbto;

    [RfcField(AbapName = "NUM_DOC_PEDIDO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 138)]
    [XmlElement("NUM_DOC_PEDIDO")]
    public string Num_Doc_Pedido
    { 
       get
       {
          return _Num_Doc_Pedido;
       }
       set
       {
          _Num_Doc_Pedido = value;
       }
    }
    private string _Num_Doc_Pedido;

    [RfcField(AbapName = "NUM_DOC_DEVOL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 139)]
    [XmlElement("NUM_DOC_DEVOL")]
    public string Num_Doc_Devol
    { 
       get
       {
          return _Num_Doc_Devol;
       }
       set
       {
          _Num_Doc_Devol = value;
       }
    }
    private string _Num_Doc_Devol;

    [RfcField(AbapName = "NUM_DOC_NRO_PCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 140)]
    [XmlElement("NUM_DOC_NRO_PCS")]
    public string Num_Doc_Nro_Pcs
    { 
       get
       {
          return _Num_Doc_Nro_Pcs;
       }
       set
       {
          _Num_Doc_Nro_Pcs = value;
       }
    }
    private string _Num_Doc_Nro_Pcs;

    [RfcField(AbapName = "MOD_FEC_VTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 141)]
    [XmlElement("MOD_FEC_VTA")]
    public string Mod_Fec_Vta
    { 
       get
       {
          return _Mod_Fec_Vta;
       }
       set
       {
          _Mod_Fec_Vta = value;
       }
    }
    private string _Mod_Fec_Vta;

    [RfcField(AbapName = "POR_DESC_DM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 142)]
    [XmlElement("POR_DESC_DM")]
    public string Por_Desc_Dm
    { 
       get
       {
          return _Por_Desc_Dm;
       }
       set
       {
          _Por_Desc_Dm = value;
       }
    }
    private string _Por_Desc_Dm;

    [RfcField(AbapName = "COM_PREPAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 143)]
    [XmlElement("COM_PREPAGO")]
    public string Com_Prepago
    { 
       get
       {
          return _Com_Prepago;
       }
       set
       {
          _Com_Prepago = value;
       }
    }
    private string _Com_Prepago;

    [RfcField(AbapName = "COM_POSTPAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 144)]
    [XmlElement("COM_POSTPAGO")]
    public string Com_Postpago
    { 
       get
       {
          return _Com_Postpago;
       }
       set
       {
          _Com_Postpago = value;
       }
    }
    private string _Com_Postpago;

    [RfcField(AbapName = "COM_CONTROL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 145)]
    [XmlElement("COM_CONTROL")]
    public string Com_Control
    { 
       get
       {
          return _Com_Control;
       }
       set
       {
          _Com_Control = value;
       }
    }
    private string _Com_Control;

    [RfcField(AbapName = "COM_REC_VIRTUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 146)]
    [XmlElement("COM_REC_VIRTUAL")]
    public string Com_Rec_Virtual
    { 
       get
       {
          return _Com_Rec_Virtual;
       }
       set
       {
          _Com_Rec_Virtual = value;
       }
    }
    private string _Com_Rec_Virtual;

    [RfcField(AbapName = "COM_REC_FISICA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 147)]
    [XmlElement("COM_REC_FISICA")]
    public string Com_Rec_Fisica
    { 
       get
       {
          return _Com_Rec_Fisica;
       }
       set
       {
          _Com_Rec_Fisica = value;
       }
    }
    private string _Com_Rec_Fisica;

    [RfcField(AbapName = "COM_DEV_DOA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 148)]
    [XmlElement("COM_DEV_DOA")]
    public string Com_Dev_Doa
    { 
       get
       {
          return _Com_Dev_Doa;
       }
       set
       {
          _Com_Dev_Doa = value;
       }
    }
    private string _Com_Dev_Doa;

    [RfcField(AbapName = "COM_DEV_CUS_CARE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 149)]
    [XmlElement("COM_DEV_CUS_CARE")]
    public string Com_Dev_Cus_Care
    { 
       get
       {
          return _Com_Dev_Cus_Care;
       }
       set
       {
          _Com_Dev_Cus_Care = value;
       }
    }
    private string _Com_Dev_Cus_Care;

    [RfcField(AbapName = "COM_DEV_COBER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 150)]
    [XmlElement("COM_DEV_COBER")]
    public string Com_Dev_Cober
    { 
       get
       {
          return _Com_Dev_Cober;
       }
       set
       {
          _Com_Dev_Cober = value;
       }
    }
    private string _Com_Dev_Cober;

    [RfcField(AbapName = "COM_REPOS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 151)]
    [XmlElement("COM_REPOS")]
    public string Com_Repos
    { 
       get
       {
          return _Com_Repos;
       }
       set
       {
          _Com_Repos = value;
       }
    }
    private string _Com_Repos;

    [RfcField(AbapName = "COM_REPOS_SERT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 152)]
    [XmlElement("COM_REPOS_SERT")]
    public string Com_Repos_Sert
    { 
       get
       {
          return _Com_Repos_Sert;
       }
       set
       {
          _Com_Repos_Sert = value;
       }
    }
    private string _Com_Repos_Sert;

    [RfcField(AbapName = "COM_FIDELIZA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 153)]
    [XmlElement("COM_FIDELIZA")]
    public string Com_Fideliza
    { 
       get
       {
          return _Com_Fideliza;
       }
       set
       {
          _Com_Fideliza = value;
       }
    }
    private string _Com_Fideliza;

    [RfcField(AbapName = "COM_M_PRE_POST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 154)]
    [XmlElement("COM_M_PRE_POST")]
    public string Com_M_Pre_Post
    { 
       get
       {
          return _Com_M_Pre_Post;
       }
       set
       {
          _Com_M_Pre_Post = value;
       }
    }
    private string _Com_M_Pre_Post;

    [RfcField(AbapName = "COM_M_POST_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 155)]
    [XmlElement("COM_M_POST_PRE")]
    public string Com_M_Post_Pre
    { 
       get
       {
          return _Com_M_Post_Pre;
       }
       set
       {
          _Com_M_Post_Pre = value;
       }
    }
    private string _Com_M_Post_Pre;

    [RfcField(AbapName = "COM_M_PRE_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 156)]
    [XmlElement("COM_M_PRE_CTRL")]
    public string Com_M_Pre_Ctrl
    { 
       get
       {
          return _Com_M_Pre_Ctrl;
       }
       set
       {
          _Com_M_Pre_Ctrl = value;
       }
    }
    private string _Com_M_Pre_Ctrl;

    [RfcField(AbapName = "COM_M_POST_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 157)]
    [XmlElement("COM_M_POST_CTRL")]
    public string Com_M_Post_Ctrl
    { 
       get
       {
          return _Com_M_Post_Ctrl;
       }
       set
       {
          _Com_M_Post_Ctrl = value;
       }
    }
    private string _Com_M_Post_Ctrl;

    [RfcField(AbapName = "COM_M_CTRL_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 158)]
    [XmlElement("COM_M_CTRL_PRE")]
    public string Com_M_Ctrl_Pre
    { 
       get
       {
          return _Com_M_Ctrl_Pre;
       }
       set
       {
          _Com_M_Ctrl_Pre = value;
       }
    }
    private string _Com_M_Ctrl_Pre;

    [RfcField(AbapName = "COM_M_CTRL_POS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 159)]
    [XmlElement("COM_M_CTRL_POS")]
    public string Com_M_Ctrl_Pos
    { 
       get
       {
          return _Com_M_Ctrl_Pos;
       }
       set
       {
          _Com_M_Ctrl_Pos = value;
       }
    }
    private string _Com_M_Ctrl_Pos;

    [RfcField(AbapName = "COM_M_REN_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 160)]
    [XmlElement("COM_M_REN_PRE")]
    public string Com_M_Ren_Pre
    { 
       get
       {
          return _Com_M_Ren_Pre;
       }
       set
       {
          _Com_M_Ren_Pre = value;
       }
    }
    private string _Com_M_Ren_Pre;

    [RfcField(AbapName = "COM_M_REN_POS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 161)]
    [XmlElement("COM_M_REN_POS")]
    public string Com_M_Ren_Pos
    { 
       get
       {
          return _Com_M_Ren_Pos;
       }
       set
       {
          _Com_M_Ren_Pos = value;
       }
    }
    private string _Com_M_Ren_Pos;

    [RfcField(AbapName = "COM_M_REN_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 162)]
    [XmlElement("COM_M_REN_CTRL")]
    public string Com_M_Ren_Ctrl
    { 
       get
       {
          return _Com_M_Ren_Ctrl;
       }
       set
       {
          _Com_M_Ren_Ctrl = value;
       }
    }
    private string _Com_M_Ren_Ctrl;

    [RfcField(AbapName = "VENTA_POSTPAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 163)]
    [XmlElement("VENTA_POSTPAGO")]
    public string Venta_Postpago
    { 
       get
       {
          return _Venta_Postpago;
       }
       set
       {
          _Venta_Postpago = value;
       }
    }
    private string _Venta_Postpago;

    [RfcField(AbapName = "VENTA_PREPAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 164)]
    [XmlElement("VENTA_PREPAGO")]
    public string Venta_Prepago
    { 
       get
       {
          return _Venta_Prepago;
       }
       set
       {
          _Venta_Prepago = value;
       }
    }
    private string _Venta_Prepago;

    [RfcField(AbapName = "VENTA_CONTROL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 165)]
    [XmlElement("VENTA_CONTROL")]
    public string Venta_Control
    { 
       get
       {
          return _Venta_Control;
       }
       set
       {
          _Venta_Control = value;
       }
    }
    private string _Venta_Control;

    [RfcField(AbapName = "VENTA_REC_FIS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 166)]
    [XmlElement("VENTA_REC_FIS")]
    public string Venta_Rec_Fis
    { 
       get
       {
          return _Venta_Rec_Fis;
       }
       set
       {
          _Venta_Rec_Fis = value;
       }
    }
    private string _Venta_Rec_Fis;

    [RfcField(AbapName = "VENTA_REC_VIR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 167)]
    [XmlElement("VENTA_REC_VIR")]
    public string Venta_Rec_Vir
    { 
       get
       {
          return _Venta_Rec_Vir;
       }
       set
       {
          _Venta_Rec_Vir = value;
       }
    }
    private string _Venta_Rec_Vir;

    [RfcField(AbapName = "DEVOL_DOA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 168)]
    [XmlElement("DEVOL_DOA")]
    public string Devol_Doa
    { 
       get
       {
          return _Devol_Doa;
       }
       set
       {
          _Devol_Doa = value;
       }
    }
    private string _Devol_Doa;

    [RfcField(AbapName = "DEVOL_CUST_CARE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 169)]
    [XmlElement("DEVOL_CUST_CARE")]
    public string Devol_Cust_Care
    { 
       get
       {
          return _Devol_Cust_Care;
       }
       set
       {
          _Devol_Cust_Care = value;
       }
    }
    private string _Devol_Cust_Care;

    [RfcField(AbapName = "DEVOL_COBERTURA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 170)]
    [XmlElement("DEVOL_COBERTURA")]
    public string Devol_Cobertura
    { 
       get
       {
          return _Devol_Cobertura;
       }
       set
       {
          _Devol_Cobertura = value;
       }
    }
    private string _Devol_Cobertura;

    [RfcField(AbapName = "DEVOL_DINERO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 171)]
    [XmlElement("DEVOL_DINERO")]
    public string Devol_Dinero
    { 
       get
       {
          return _Devol_Dinero;
       }
       set
       {
          _Devol_Dinero = value;
       }
    }
    private string _Devol_Dinero;

    [RfcField(AbapName = "DEVOL_PLAZO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 3, Offset = 172)]
    [XmlElement("DEVOL_PLAZO")]
    public Decimal Devol_Plazo
    { 
       get
       {
          return _Devol_Plazo;
       }
       set
       {
          _Devol_Plazo = value;
       }
    }
    private Decimal _Devol_Plazo;

    [RfcField(AbapName = "REPOSICION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 175)]
    [XmlElement("REPOSICION")]
    public string Reposicion
    { 
       get
       {
          return _Reposicion;
       }
       set
       {
          _Reposicion = value;
       }
    }
    private string _Reposicion;

    [RfcField(AbapName = "REPOS_SEGURO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 176)]
    [XmlElement("REPOS_SEGURO")]
    public string Repos_Seguro
    { 
       get
       {
          return _Repos_Seguro;
       }
       set
       {
          _Repos_Seguro = value;
       }
    }
    private string _Repos_Seguro;

    [RfcField(AbapName = "FIDELIZACION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 177)]
    [XmlElement("FIDELIZACION")]
    public string Fidelizacion
    { 
       get
       {
          return _Fidelizacion;
       }
       set
       {
          _Fidelizacion = value;
       }
    }
    private string _Fidelizacion;

    [RfcField(AbapName = "MGR_PRE_POST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 178)]
    [XmlElement("MGR_PRE_POST")]
    public string Mgr_Pre_Post
    { 
       get
       {
          return _Mgr_Pre_Post;
       }
       set
       {
          _Mgr_Pre_Post = value;
       }
    }
    private string _Mgr_Pre_Post;

    [RfcField(AbapName = "MGR_POST_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 179)]
    [XmlElement("MGR_POST_PRE")]
    public string Mgr_Post_Pre
    { 
       get
       {
          return _Mgr_Post_Pre;
       }
       set
       {
          _Mgr_Post_Pre = value;
       }
    }
    private string _Mgr_Post_Pre;

    [RfcField(AbapName = "MGR_PRE_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 180)]
    [XmlElement("MGR_PRE_CTRL")]
    public string Mgr_Pre_Ctrl
    { 
       get
       {
          return _Mgr_Pre_Ctrl;
       }
       set
       {
          _Mgr_Pre_Ctrl = value;
       }
    }
    private string _Mgr_Pre_Ctrl;

    [RfcField(AbapName = "MGR_CTRL_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 181)]
    [XmlElement("MGR_CTRL_PRE")]
    public string Mgr_Ctrl_Pre
    { 
       get
       {
          return _Mgr_Ctrl_Pre;
       }
       set
       {
          _Mgr_Ctrl_Pre = value;
       }
    }
    private string _Mgr_Ctrl_Pre;

    [RfcField(AbapName = "MGR_POST_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 182)]
    [XmlElement("MGR_POST_CTRL")]
    public string Mgr_Post_Ctrl
    { 
       get
       {
          return _Mgr_Post_Ctrl;
       }
       set
       {
          _Mgr_Post_Ctrl = value;
       }
    }
    private string _Mgr_Post_Ctrl;

    [RfcField(AbapName = "MGR_CTRL_POST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 183)]
    [XmlElement("MGR_CTRL_POST")]
    public string Mgr_Ctrl_Post
    { 
       get
       {
          return _Mgr_Ctrl_Post;
       }
       set
       {
          _Mgr_Ctrl_Post = value;
       }
    }
    private string _Mgr_Ctrl_Post;

    [RfcField(AbapName = "RENOV_PRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 184)]
    [XmlElement("RENOV_PRE")]
    public string Renov_Pre
    { 
       get
       {
          return _Renov_Pre;
       }
       set
       {
          _Renov_Pre = value;
       }
    }
    private string _Renov_Pre;

    [RfcField(AbapName = "RENOV_CTRL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 185)]
    [XmlElement("RENOV_CTRL")]
    public string Renov_Ctrl
    { 
       get
       {
          return _Renov_Ctrl;
       }
       set
       {
          _Renov_Ctrl = value;
       }
    }
    private string _Renov_Ctrl;

    [RfcField(AbapName = "RENOV_POST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 186)]
    [XmlElement("RENOV_POST")]
    public string Renov_Post
    { 
       get
       {
          return _Renov_Post;
       }
       set
       {
          _Renov_Post = value;
       }
    }
    private string _Renov_Post;

    [RfcField(AbapName = "SERV_TECNICO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 187)]
    [XmlElement("SERV_TECNICO")]
    public string Serv_Tecnico
    { 
       get
       {
          return _Serv_Tecnico;
       }
       set
       {
          _Serv_Tecnico = value;
       }
    }
    private string _Serv_Tecnico;

    [RfcField(AbapName = "VTA_NO_ASOCIADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 188)]
    [XmlElement("VTA_NO_ASOCIADO")]
    public string Vta_No_Asociado
    { 
       get
       {
          return _Vta_No_Asociado;
       }
       set
       {
          _Vta_No_Asociado = value;
       }
    }
    private string _Vta_No_Asociado;

    [RfcField(AbapName = "NRO_CARIFY", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 189)]
    [XmlElement("NRO_CARIFY")]
    public string Nro_Carify
    { 
       get
       {
          return _Nro_Carify;
       }
       set
       {
          _Nro_Carify = value;
       }
    }
    private string _Nro_Carify;

    [RfcField(AbapName = "MONTO_MIN_RECAR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 190)]
    [XmlElement("MONTO_MIN_RECAR")]
    public Decimal Monto_Min_Recar
    { 
       get
       {
          return _Monto_Min_Recar;
       }
       set
       {
          _Monto_Min_Recar = value;
       }
    }
    private Decimal _Monto_Min_Recar;

    [RfcField(AbapName = "MONTO_MAX_RECAR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 196)]
    [XmlElement("MONTO_MAX_RECAR")]
    public Decimal Monto_Max_Recar
    { 
       get
       {
          return _Monto_Max_Recar;
       }
       set
       {
          _Monto_Max_Recar = value;
       }
    }
    private Decimal _Monto_Max_Recar;

    [RfcField(AbapName = "VERSION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 202)]
    [XmlElement("VERSION")]
    public string Version
    { 
       get
       {
          return _Version;
       }
       set
       {
          _Version = value;
       }
    }
    private string _Version;

    [RfcField(AbapName = "PRIMERA_CUOTA", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 4, Decimals = 2, Offset = 205)]
    [XmlElement("PRIMERA_CUOTA")]
    public Decimal Primera_Cuota
    { 
       get
       {
          return _Primera_Cuota;
       }
       set
       {
          _Primera_Cuota = value;
       }
    }
    private Decimal _Primera_Cuota;

    [RfcField(AbapName = "TRANSF_GRATUITA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 209)]
    [XmlElement("TRANSF_GRATUITA")]
    public string Transf_Gratuita
    { 
       get
       {
          return _Transf_Gratuita;
       }
       set
       {
          _Transf_Gratuita = value;
       }
    }
    private string _Transf_Gratuita;

    [RfcField(AbapName = "VENTA_CUOTAS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 210)]
    [XmlElement("VENTA_CUOTAS")]
    public string Venta_Cuotas
    { 
       get
       {
          return _Venta_Cuotas;
       }
       set
       {
          _Venta_Cuotas = value;
       }
    }
    private string _Venta_Cuotas;

    [RfcField(AbapName = "BOLETA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 211)]
    [XmlElement("BOLETA")]
    public string Boleta
    { 
       get
       {
          return _Boleta;
       }
       set
       {
          _Boleta = value;
       }
    }
    private string _Boleta;

    [RfcField(AbapName = "FACTURA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 212)]
    [XmlElement("FACTURA")]
    public string Factura
    { 
       get
       {
          return _Factura;
       }
       set
       {
          _Factura = value;
       }
    }
    private string _Factura;

    [RfcField(AbapName = "NOTA_CREDITO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 213)]
    [XmlElement("NOTA_CREDITO")]
    public string Nota_Credito
    { 
       get
       {
          return _Nota_Credito;
       }
       set
       {
          _Nota_Credito = value;
       }
    }
    private string _Nota_Credito;

    [RfcField(AbapName = "NOTA_DEBITO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 214)]
    [XmlElement("NOTA_DEBITO")]
    public string Nota_Debito
    { 
       get
       {
          return _Nota_Debito;
       }
       set
       {
          _Nota_Debito = value;
       }
    }
    private string _Nota_Debito;

    [RfcField(AbapName = "NOTA_PEDIDO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 215)]
    [XmlElement("NOTA_PEDIDO")]
    public string Nota_Pedido
    { 
       get
       {
          return _Nota_Pedido;
       }
       set
       {
          _Nota_Pedido = value;
       }
    }
    private string _Nota_Pedido;

    [RfcField(AbapName = "NOTA_DEVOLUCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 216)]
    [XmlElement("NOTA_DEVOLUCION")]
    public string Nota_Devolucion
    { 
       get
       {
          return _Nota_Devolucion;
       }
       set
       {
          _Nota_Devolucion = value;
       }
    }
    private string _Nota_Devolucion;

    [RfcField(AbapName = "NUMERO_PCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 217)]
    [XmlElement("NUMERO_PCS")]
    public string Numero_Pcs
    { 
       get
       {
          return _Numero_Pcs;
       }
       set
       {
          _Numero_Pcs = value;
       }
    }
    private string _Numero_Pcs;

    [RfcField(AbapName = "DOC_ACTUALIZADO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 218)]
    [XmlElement("DOC_ACTUALIZADO")]
    public string Doc_Actualizado
    { 
       get
       {
          return _Doc_Actualizado;
       }
       set
       {
          _Doc_Actualizado = value;
       }
    }
    private string _Doc_Actualizado;

    [RfcField(AbapName = "DOC_EMITE_MKT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 219)]
    [XmlElement("DOC_EMITE_MKT")]
    public string Doc_Emite_Mkt
    { 
       get
       {
          return _Doc_Emite_Mkt;
       }
       set
       {
          _Doc_Emite_Mkt = value;
       }
    }
    private string _Doc_Emite_Mkt;

    [RfcField(AbapName = "SERT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 220)]
    [XmlElement("SERT")]
    public string Sert
    { 
       get
       {
          return _Sert;
       }
       set
       {
          _Sert = value;
       }
    }
    private string _Sert;

    [RfcField(AbapName = "CARGO_AUTOMATICO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 221)]
    [XmlElement("CARGO_AUTOMATICO")]
    public string Cargo_Automatico
    { 
       get
       {
          return _Cargo_Automatico;
       }
       set
       {
          _Cargo_Automatico = value;
       }
    }
    private string _Cargo_Automatico;

    [RfcField(AbapName = "METAFRAME", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 222)]
    [XmlElement("METAFRAME")]
    public string Metaframe
    { 
       get
       {
          return _Metaframe;
       }
       set
       {
          _Metaframe = value;
       }
    }
    private string _Metaframe;

    [RfcField(AbapName = "MONTO_RECAR_VIRT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 223)]
    [XmlElement("MONTO_RECAR_VIRT")]
    public Decimal Monto_Recar_Virt
    { 
       get
       {
          return _Monto_Recar_Virt;
       }
       set
       {
          _Monto_Recar_Virt = value;
       }
    }
    private Decimal _Monto_Recar_Virt;

    [RfcField(AbapName = "SALDO_RECAR_VIRT", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 231)]
    [XmlElement("SALDO_RECAR_VIRT")]
    public Decimal Saldo_Recar_Virt
    { 
       get
       {
          return _Saldo_Recar_Virt;
       }
       set
       {
          _Saldo_Recar_Virt = value;
       }
    }
    private Decimal _Saldo_Recar_Virt;

    [RfcField(AbapName = "INHAB_PAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 239)]
    [XmlElement("INHAB_PAGO")]
    public string Inhab_Pago
    { 
       get
       {
          return _Inhab_Pago;
       }
       set
       {
          _Inhab_Pago = value;
       }
    }
    private string _Inhab_Pago;

    [RfcField(AbapName = "COD_CLTE_VARIOS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 240)]
    [XmlElement("COD_CLTE_VARIOS")]
    public string Cod_Clte_Varios
    { 
       get
       {
          return _Cod_Clte_Varios;
       }
       set
       {
          _Cod_Clte_Varios = value;
       }
    }
    private string _Cod_Clte_Varios;

    [RfcField(AbapName = "IND_ACTIV_BSCS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 256)]
    [XmlElement("IND_ACTIV_BSCS")]
    public string Ind_Activ_Bscs
    { 
       get
       {
          return _Ind_Activ_Bscs;
       }
       set
       {
          _Ind_Activ_Bscs = value;
       }
    }
    private string _Ind_Activ_Bscs;

    [RfcField(AbapName = "CREAR_LOG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 257)]
    [XmlElement("CREAR_LOG")]
    public string Crear_Log
    { 
       get
       {
          return _Crear_Log;
       }
       set
       {
          _Crear_Log = value;
       }
    }
    private string _Crear_Log;

    [RfcField(AbapName = "IND_DOC_CHIP_REP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 258)]
    [XmlElement("IND_DOC_CHIP_REP")]
    public string Ind_Doc_Chip_Rep
    { 
       get
       {
          return _Ind_Doc_Chip_Rep;
       }
       set
       {
          _Ind_Doc_Chip_Rep = value;
       }
    }
    private string _Ind_Doc_Chip_Rep;

    [RfcField(AbapName = "VAL_VEND_POST", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 259)]
    [XmlElement("VAL_VEND_POST")]
    public string Val_Vend_Post
    { 
       get
       {
          return _Val_Vend_Post;
       }
       set
       {
          _Val_Vend_Post = value;
       }
    }
    private string _Val_Vend_Post;

    [RfcField(AbapName = "VALOR_ROAMING", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 260)]
    [XmlElement("VALOR_ROAMING")]
    public Decimal Valor_Roaming
    { 
       get
       {
          return _Valor_Roaming;
       }
       set
       {
          _Valor_Roaming = value;
       }
    }
    private Decimal _Valor_Roaming;

    [RfcField(AbapName = "LIMITE_CREDITO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 266)]
    [XmlElement("LIMITE_CREDITO")]
    public Decimal Limite_Credito
    { 
       get
       {
          return _Limite_Credito;
       }
       set
       {
          _Limite_Credito = value;
       }
    }
    private Decimal _Limite_Credito;

    [RfcField(AbapName = "LIM_CRED_RECUR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 274)]
    [XmlElement("LIM_CRED_RECUR")]
    public Decimal Lim_Cred_Recur
    { 
       get
       {
          return _Lim_Cred_Recur;
       }
       set
       {
          _Lim_Cred_Recur = value;
       }
    }
    private Decimal _Lim_Cred_Recur;

    [RfcField(AbapName = "REGION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 282)]
    [XmlElement("REGION")]
    public string Region
    { 
       get
       {
          return _Region;
       }
       set
       {
          _Region = value;
       }
    }
    private string _Region;

    [RfcField(AbapName = "DEN_REGION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 285)]
    [XmlElement("DEN_REGION")]
    public string Den_Region
    { 
       get
       {
          return _Den_Region;
       }
       set
       {
          _Den_Region = value;
       }
    }
    private string _Den_Region;

    [RfcField(AbapName = "TIEMPO_BLOQUEO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 3, Offset = 305)]
    [XmlElement("TIEMPO_BLOQUEO")]
    public string Tiempo_Bloqueo
    { 
       get
       {
          return _Tiempo_Bloqueo;
       }
       set
       {
          _Tiempo_Bloqueo = value;
       }
    }
    private string _Tiempo_Bloqueo;

    [RfcField(AbapName = "IND_REF_CORNER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 308)]
    [XmlElement("IND_REF_CORNER")]
    public string Ind_Ref_Corner
    { 
       get
       {
          return _Ind_Ref_Corner;
       }
       set
       {
          _Ind_Ref_Corner = value;
       }
    }
    private string _Ind_Ref_Corner;

    [RfcField(AbapName = "VIG_CONS_RECURR", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 309)]
    [XmlElement("VIG_CONS_RECURR")]
    public string Vig_Cons_Recurr
    { 
       get
       {
          return _Vig_Cons_Recurr;
       }
       set
       {
          _Vig_Cons_Recurr = value;
       }
    }
    private string _Vig_Cons_Recurr;

    [RfcField(AbapName = "FLG_ACTIV_RECURR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 311)]
    [XmlElement("FLG_ACTIV_RECURR")]
    public string Flg_Activ_Recurr
    { 
       get
       {
          return _Flg_Activ_Recurr;
       }
       set
       {
          _Flg_Activ_Recurr = value;
       }
    }
    private string _Flg_Activ_Recurr;

    [RfcField(AbapName = "REN_REP_HDC", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 312)]
    [XmlElement("REN_REP_HDC")]
    public string Ren_Rep_Hdc
    { 
       get
       {
          return _Ren_Rep_Hdc;
       }
       set
       {
          _Ren_Rep_Hdc = value;
       }
    }
    private string _Ren_Rep_Hdc;

    [RfcField(AbapName = "IMPRESION_SAP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 313)]
    [XmlElement("IMPRESION_SAP")]
    public string Impresion_Sap
    { 
       get
       {
          return _Impresion_Sap;
       }
       set
       {
          _Impresion_Sap = value;
       }
    }
    private string _Impresion_Sap;

    [RfcField(AbapName = "FACT_REP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 314)]
    [XmlElement("FACT_REP")]
    public string Fact_Rep
    { 
       get
       {
          return _Fact_Rep;
       }
       set
       {
          _Fact_Rep = value;
       }
    }
    private string _Fact_Rep;

  }

}
