
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 19/09/2013
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PLAN_SERV" , Length = 63)]
  public class ZST_PLAN_SERV : SAPStructure
  {
    
    [RfcField(AbapName = "PLAN_TARIFARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 0)]
    [XmlElement("PLAN_TARIFARIO")]
    public string Plan_Tarifario
    { 
       get
       {
          return _Plan_Tarifario;
       }
       set
       {
          _Plan_Tarifario = value;
       }
    }
    private string _Plan_Tarifario;

    [RfcField(AbapName = "SERVICIO_SOLICIT", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 3)]
    [XmlElement("SERVICIO_SOLICIT")]
    public string Servicio_Solicit
    { 
       get
       {
          return _Servicio_Solicit;
       }
       set
       {
          _Servicio_Solicit = value;
       }
    }
    private string _Servicio_Solicit;

    [RfcField(AbapName = "DESCRIPCION", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 7)]
    [XmlElement("DESCRIPCION")]
    public string Descripcion
    { 
       get
       {
          return _Descripcion;
       }
       set
       {
          _Descripcion = value;
       }
    }
    private string _Descripcion;

    [RfcField(AbapName = "ORDEN", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 4, Offset = 47)]
    [XmlElement("ORDEN")]
    public string Orden
    { 
       get
       {
          return _Orden;
       }
       set
       {
          _Orden = value;
       }
    }
    private string _Orden;

    [RfcField(AbapName = "GRUPO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 51)]
    [XmlElement("GRUPO")]
    public string Grupo
    { 
       get
       {
          return _Grupo;
       }
       set
       {
          _Grupo = value;
       }
    }
    private string _Grupo;

    [RfcField(AbapName = "CARGO_FIJO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 54)]
    [XmlElement("CARGO_FIJO")]
    public Decimal Cargo_Fijo
    { 
       get
       {
          return _Cargo_Fijo;
       }
       set
       {
          _Cargo_Fijo = value;
       }
    }
    private Decimal _Cargo_Fijo;

    [RfcField(AbapName = "SELECCIONABLE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 62)]
    [XmlElement("SELECCIONABLE")]
    public string Seleccionable
    { 
       get
       {
          return _Seleccionable;
       }
       set
       {
          _Seleccionable = value;
       }
    }
    private string _Seleccionable;

  }

}
