
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_ACT_CHIP" , Length = 158)]
  public class ZST_ACT_CHIP : SAPStructure
  {
    
    [RfcField(AbapName = "NRO_SOLICITUD", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("NRO_SOLICITUD")]
    public string Nro_Solicitud
    { 
       get
       {
          return _Nro_Solicitud;
       }
       set
       {
          _Nro_Solicitud = value;
       }
    }
    private string _Nro_Solicitud;

    [RfcField(AbapName = "NRO_TELEFONO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 10)]
    [XmlElement("NRO_TELEFONO")]
    public string Nro_Telefono
    { 
       get
       {
          return _Nro_Telefono;
       }
       set
       {
          _Nro_Telefono = value;
       }
    }
    private string _Nro_Telefono;

    [RfcField(AbapName = "SERIE_ACTUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 25)]
    [XmlElement("SERIE_ACTUAL")]
    public string Serie_Actual
    { 
       get
       {
          return _Serie_Actual;
       }
       set
       {
          _Serie_Actual = value;
       }
    }
    private string _Serie_Actual;

    [RfcField(AbapName = "IMSI_ACTUAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 45)]
    [XmlElement("IMSI_ACTUAL")]
    public string Imsi_Actual
    { 
       get
       {
          return _Imsi_Actual;
       }
       set
       {
          _Imsi_Actual = value;
       }
    }
    private string _Imsi_Actual;

    [RfcField(AbapName = "OFICINA_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 60)]
    [XmlElement("OFICINA_VENTA")]
    public string Oficina_Venta
    { 
       get
       {
          return _Oficina_Venta;
       }
       set
       {
          _Oficina_Venta = value;
       }
    }
    private string _Oficina_Venta;

    [RfcField(AbapName = "DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 64)]
    [XmlElement("DOCUMENTO")]
    public string Documento
    { 
       get
       {
          return _Documento;
       }
       set
       {
          _Documento = value;
       }
    }
    private string _Documento;

    [RfcField(AbapName = "MOTIVO_PEDIDO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 74)]
    [XmlElement("MOTIVO_PEDIDO")]
    public string Motivo_Pedido
    { 
       get
       {
          return _Motivo_Pedido;
       }
       set
       {
          _Motivo_Pedido = value;
       }
    }
    private string _Motivo_Pedido;

    [RfcField(AbapName = "SERIE_NUEVA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 77)]
    [XmlElement("SERIE_NUEVA")]
    public string Serie_Nueva
    { 
       get
       {
          return _Serie_Nueva;
       }
       set
       {
          _Serie_Nueva = value;
       }
    }
    private string _Serie_Nueva;

    [RfcField(AbapName = "IMSI_NUEVO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 97)]
    [XmlElement("IMSI_NUEVO")]
    public string Imsi_Nuevo
    { 
       get
       {
          return _Imsi_Nuevo;
       }
       set
       {
          _Imsi_Nuevo = value;
       }
    }
    private string _Imsi_Nuevo;

    [RfcField(AbapName = "VENDEDOR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 112)]
    [XmlElement("VENDEDOR")]
    public string Vendedor
    { 
       get
       {
          return _Vendedor;
       }
       set
       {
          _Vendedor = value;
       }
    }
    private string _Vendedor;

    [RfcField(AbapName = "ESTADO_INI_TELEF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 122)]
    [XmlElement("ESTADO_INI_TELEF")]
    public string Estado_Ini_Telef
    { 
       get
       {
          return _Estado_Ini_Telef;
       }
       set
       {
          _Estado_Ini_Telef = value;
       }
    }
    private string _Estado_Ini_Telef;

    [RfcField(AbapName = "FECHA_CREACION", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 125)]
    [XmlElement("FECHA_CREACION")]
    public string Fecha_Creacion
    { 
       get
       {
          return _Fecha_Creacion;
       }
       set
       {
          _Fecha_Creacion = value;
       }
    }
    private string _Fecha_Creacion;

    [RfcField(AbapName = "HORA_CREACION", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 133)]
    [XmlElement("HORA_CREACION")]
    public string Hora_Creacion
    { 
       get
       {
          return _Hora_Creacion;
       }
       set
       {
          _Hora_Creacion = value;
       }
    }
    private string _Hora_Creacion;

    [RfcField(AbapName = "ESTADO_SOLICITUD", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 139)]
    [XmlElement("ESTADO_SOLICITUD")]
    public string Estado_Solicitud
    { 
       get
       {
          return _Estado_Solicitud;
       }
       set
       {
          _Estado_Solicitud = value;
       }
    }
    private string _Estado_Solicitud;

    [RfcField(AbapName = "ENVIADO_VARIACIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 140)]
    [XmlElement("ENVIADO_VARIACIO")]
    public string Enviado_Variacio
    { 
       get
       {
          return _Enviado_Variacio;
       }
       set
       {
          _Enviado_Variacio = value;
       }
    }
    private string _Enviado_Variacio;

    [RfcField(AbapName = "ESTADO_FIN_TELEF", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 141)]
    [XmlElement("ESTADO_FIN_TELEF")]
    public string Estado_Fin_Telef
    { 
       get
       {
          return _Estado_Fin_Telef;
       }
       set
       {
          _Estado_Fin_Telef = value;
       }
    }
    private string _Estado_Fin_Telef;

    [RfcField(AbapName = "FECHA_ACTUALIZ", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 144)]
    [XmlElement("FECHA_ACTUALIZ")]
    public string Fecha_Actualiz
    { 
       get
       {
          return _Fecha_Actualiz;
       }
       set
       {
          _Fecha_Actualiz = value;
       }
    }
    private string _Fecha_Actualiz;

    [RfcField(AbapName = "HORA_ACTUALIZ", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 152)]
    [XmlElement("HORA_ACTUALIZ")]
    public string Hora_Actualiz
    { 
       get
       {
          return _Hora_Actualiz;
       }
       set
       {
          _Hora_Actualiz = value;
       }
    }
    private string _Hora_Actualiz;

  }

}
