
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_VENDEDOR" , Length = 275)]
  public class ZST_PV_VENDEDOR : SAPStructure
  {
    
    [RfcField(AbapName = "USUARIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 0)]
    [XmlElement("USUARIO")]
    public string Usuario
    { 
       get
       {
          return _Usuario;
       }
       set
       {
          _Usuario = value;
       }
    }
    private string _Usuario;

    [RfcField(AbapName = "NOMBRE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 10)]
    [XmlElement("NOMBRE")]
    public string Nombre
    { 
       get
       {
          return _Nombre;
       }
       set
       {
          _Nombre = value;
       }
    }
    private string _Nombre;

    [RfcField(AbapName = "TELEFONO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 15, Offset = 50)]
    [XmlElement("TELEFONO")]
    public string Telefono
    { 
       get
       {
          return _Telefono;
       }
       set
       {
          _Telefono = value;
       }
    }
    private string _Telefono;

    [RfcField(AbapName = "OFICINA_VENTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 65)]
    [XmlElement("OFICINA_VENTA")]
    public string Oficina_Venta
    { 
       get
       {
          return _Oficina_Venta;
       }
       set
       {
          _Oficina_Venta = value;
       }
    }
    private string _Oficina_Venta;

    [RfcField(AbapName = "OFICINA_ALTER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 69)]
    [XmlElement("OFICINA_ALTER")]
    public string Oficina_Alter
    { 
       get
       {
          return _Oficina_Alter;
       }
       set
       {
          _Oficina_Alter = value;
       }
    }
    private string _Oficina_Alter;

    [RfcField(AbapName = "TIPO_DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 2, Offset = 73)]
    [XmlElement("TIPO_DOCUMENTO")]
    public string Tipo_Documento
    { 
       get
       {
          return _Tipo_Documento;
       }
       set
       {
          _Tipo_Documento = value;
       }
    }
    private string _Tipo_Documento;

    [RfcField(AbapName = "OBSERVACIONES", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 200, Offset = 75)]
    [XmlElement("OBSERVACIONES")]
    public string Observaciones
    { 
       get
       {
          return _Observaciones;
       }
       set
       {
          _Observaciones = value;
       }
    }
    private string _Observaciones;

  }

}
