
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_LOG" , Length = 221)]
  public class ZST_PV_LOG : SAPStructure
  {
    
    [RfcField(AbapName = "TYPE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 0)]
    [XmlElement("TYPE")]
    public string Type
    { 
       get
       {
          return _Type;
       }
       set
       {
          _Type = value;
       }
    }
    private string _Type;

    [RfcField(AbapName = "MSG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 220, Offset = 1)]
    [XmlElement("MSG")]
    public string Msg
    { 
       get
       {
          return _Msg;
       }
       set
       {
          _Msg = value;
       }
    }
    private string _Msg;

  }

}
