
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_LIN_DOC_IMEI" , Length = 52)]
  public class ZST_PV_LIN_DOC_IMEI : SAPStructure
  {
    
    [RfcField(AbapName = "DOCUMENTO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 0)]
    [XmlElement("DOCUMENTO")]
    public string Documento
    { 
       get
       {
          return _Documento;
       }
       set
       {
          _Documento = value;
       }
    }
    private string _Documento;

    [RfcField(AbapName = "CONSECUTIVO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 6, Offset = 10)]
    [XmlElement("CONSECUTIVO")]
    public string Consecutivo
    { 
       get
       {
          return _Consecutivo;
       }
       set
       {
          _Consecutivo = value;
       }
    }
    private string _Consecutivo;

    [RfcField(AbapName = "SERIE_INICIAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 16)]
    [XmlElement("SERIE_INICIAL")]
    public string Serie_Inicial
    { 
       get
       {
          return _Serie_Inicial;
       }
       set
       {
          _Serie_Inicial = value;
       }
    }
    private string _Serie_Inicial;

    [RfcField(AbapName = "SERIE_FINAL", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 34)]
    [XmlElement("SERIE_FINAL")]
    public string Serie_Final
    { 
       get
       {
          return _Serie_Final;
       }
       set
       {
          _Serie_Final = value;
       }
    }
    private string _Serie_Final;

  }

}
