
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 25/08/2011
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZST_PV_POOL_PAGOS" , Length = 343)]
  public class ZST_PV_POOL_PAGOS : SAPStructure
  {
    
    [RfcField(AbapName = "STATUS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 0)]
    [XmlElement("STATUS")]
    public string Status
    { 
       get
       {
          return _Status;
       }
       set
       {
          _Status = value;
       }
    }
    private string _Status;

    [RfcField(AbapName = "BUKRS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 4)]
    [XmlElement("BUKRS")]
    public string Bukrs
    { 
       get
       {
          return _Bukrs;
       }
       set
       {
          _Bukrs = value;
       }
    }
    private string _Bukrs;

    [RfcField(AbapName = "VBELN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 8)]
    [XmlElement("VBELN")]
    public string Vbeln
    { 
       get
       {
          return _Vbeln;
       }
       set
       {
          _Vbeln = value;
       }
    }
    private string _Vbeln;

    [RfcField(AbapName = "FKDAT", RfcType = RFCTYPE.RFCTYPE_DATE, Length = 8, Offset = 18)]
    [XmlElement("FKDAT")]
    public string Fkdat
    { 
       get
       {
          return _Fkdat;
       }
       set
       {
          _Fkdat = value;
       }
    }
    private string _Fkdat;

    [RfcField(AbapName = "KUNAG", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 26)]
    [XmlElement("KUNAG")]
    public string Kunag
    { 
       get
       {
          return _Kunag;
       }
       set
       {
          _Kunag = value;
       }
    }
    private string _Kunag;

    [RfcField(AbapName = "NAME1", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 30, Offset = 42)]
    [XmlElement("NAME1")]
    public string Name1
    { 
       get
       {
          return _Name1;
       }
       set
       {
          _Name1 = value;
       }
    }
    private string _Name1;

    [RfcField(AbapName = "FKART", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 4, Offset = 72)]
    [XmlElement("FKART")]
    public string Fkart
    { 
       get
       {
          return _Fkart;
       }
       set
       {
          _Fkart = value;
       }
    }
    private string _Fkart;

    [RfcField(AbapName = "DCORTA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 15, Offset = 76)]
    [XmlElement("DCORTA")]
    public string Dcorta
    { 
       get
       {
          return _Dcorta;
       }
       set
       {
          _Dcorta = value;
       }
    }
    private string _Dcorta;

    [RfcField(AbapName = "RECIBE_PAGO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 91)]
    [XmlElement("RECIBE_PAGO")]
    public string Recibe_Pago
    { 
       get
       {
          return _Recibe_Pago;
       }
       set
       {
          _Recibe_Pago = value;
       }
    }
    private string _Recibe_Pago;

    [RfcField(AbapName = "FKSTO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 92)]
    [XmlElement("FKSTO")]
    public string Fksto
    { 
       get
       {
          return _Fksto;
       }
       set
       {
          _Fksto = value;
       }
    }
    private string _Fksto;

    [RfcField(AbapName = "XBLNR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 18, Offset = 93)]
    [XmlElement("XBLNR")]
    public string Xblnr
    { 
       get
       {
          return _Xblnr;
       }
       set
       {
          _Xblnr = value;
       }
    }
    private string _Xblnr;

    [RfcField(AbapName = "NCUOTAS", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 2, Offset = 111)]
    [XmlElement("NCUOTAS")]
    public string Ncuotas
    { 
       get
       {
          return _Ncuotas;
       }
       set
       {
          _Ncuotas = value;
       }
    }
    private string _Ncuotas;

    [RfcField(AbapName = "ABRVW", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 113)]
    [XmlElement("ABRVW")]
    public string Abrvw
    { 
       get
       {
          return _Abrvw;
       }
       set
       {
          _Abrvw = value;
       }
    }
    private string _Abrvw;

    [RfcField(AbapName = "D_ABRVW", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 116)]
    [XmlElement("D_ABRVW")]
    public string D_Abrvw
    { 
       get
       {
          return _D_Abrvw;
       }
       set
       {
          _D_Abrvw = value;
       }
    }
    private string _D_Abrvw;

    [RfcField(AbapName = "WAERK", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 5, Offset = 136)]
    [XmlElement("WAERK")]
    public string Waerk
    { 
       get
       {
          return _Waerk;
       }
       set
       {
          _Waerk = value;
       }
    }
    private string _Waerk;

    [RfcField(AbapName = "NETWR", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 141)]
    [XmlElement("NETWR")]
    public Decimal Netwr
    { 
       get
       {
          return _Netwr;
       }
       set
       {
          _Netwr = value;
       }
    }
    private Decimal _Netwr;

    [RfcField(AbapName = "MWSBK", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 7, Decimals = 2, Offset = 149)]
    [XmlElement("MWSBK")]
    public Decimal Mwsbk
    { 
       get
       {
          return _Mwsbk;
       }
       set
       {
          _Mwsbk = value;
       }
    }
    private Decimal _Mwsbk;

    [RfcField(AbapName = "TOTAL", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 156)]
    [XmlElement("TOTAL")]
    public Decimal Total
    { 
       get
       {
          return _Total;
       }
       set
       {
          _Total = value;
       }
    }
    private Decimal _Total;

    [RfcField(AbapName = "INICIAL", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 164)]
    [XmlElement("INICIAL")]
    public Decimal Inicial
    { 
       get
       {
          return _Inicial;
       }
       set
       {
          _Inicial = value;
       }
    }
    private Decimal _Inicial;

    [RfcField(AbapName = "PAGOS", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 172)]
    [XmlElement("PAGOS")]
    public Decimal Pagos
    { 
       get
       {
          return _Pagos;
       }
       set
       {
          _Pagos = value;
       }
    }
    private Decimal _Pagos;

    [RfcField(AbapName = "SALDO", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 8, Decimals = 2, Offset = 180)]
    [XmlElement("SALDO")]
    public Decimal Saldo
    { 
       get
       {
          return _Saldo;
       }
       set
       {
          _Saldo = value;
       }
    }
    private Decimal _Saldo;

    [RfcField(AbapName = "KALSM", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 6, Offset = 188)]
    [XmlElement("KALSM")]
    public string Kalsm
    { 
       get
       {
          return _Kalsm;
       }
       set
       {
          _Kalsm = value;
       }
    }
    private string _Kalsm;

    [RfcField(AbapName = "OK_ALMACEN", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 194)]
    [XmlElement("OK_ALMACEN")]
    public string Ok_Almacen
    { 
       get
       {
          return _Ok_Almacen;
       }
       set
       {
          _Ok_Almacen = value;
       }
    }
    private string _Ok_Almacen;

    [RfcField(AbapName = "OK_DESPACHO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 195)]
    [XmlElement("OK_DESPACHO")]
    public string Ok_Despacho
    { 
       get
       {
          return _Ok_Despacho;
       }
       set
       {
          _Ok_Despacho = value;
       }
    }
    private string _Ok_Despacho;

    [RfcField(AbapName = "VBTYP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 196)]
    [XmlElement("VBTYP")]
    public string Vbtyp
    { 
       get
       {
          return _Vbtyp;
       }
       set
       {
          _Vbtyp = value;
       }
    }
    private string _Vbtyp;

    [RfcField(AbapName = "ERZET", RfcType = RFCTYPE.RFCTYPE_TIME, Length = 6, Offset = 197)]
    [XmlElement("ERZET")]
    public string Erzet
    { 
       get
       {
          return _Erzet;
       }
       set
       {
          _Erzet = value;
       }
    }
    private string _Erzet;

    [RfcField(AbapName = "NRO_CONTRATO", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 203)]
    [XmlElement("NRO_CONTRATO")]
    public string Nro_Contrato
    { 
       get
       {
          return _Nro_Contrato;
       }
       set
       {
          _Nro_Contrato = value;
       }
    }
    private string _Nro_Contrato;

    [RfcField(AbapName = "NRO_OPE_INFOCORP", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 213)]
    [XmlElement("NRO_OPE_INFOCORP")]
    public string Nro_Ope_Infocorp
    { 
       get
       {
          return _Nro_Ope_Infocorp;
       }
       set
       {
          _Nro_Ope_Infocorp = value;
       }
    }
    private string _Nro_Ope_Infocorp;

    [RfcField(AbapName = "CODIGO_APROBACIO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 233)]
    [XmlElement("CODIGO_APROBACIO")]
    public string Codigo_Aprobacio
    { 
       get
       {
          return _Codigo_Aprobacio;
       }
       set
       {
          _Codigo_Aprobacio = value;
       }
    }
    private string _Codigo_Aprobacio;

    [RfcField(AbapName = "TIPO_ACTIV_CLTE", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 253)]
    [XmlElement("TIPO_ACTIV_CLTE")]
    public string Tipo_Activ_Clte
    { 
       get
       {
          return _Tipo_Activ_Clte;
       }
       set
       {
          _Tipo_Activ_Clte = value;
       }
    }
    private string _Tipo_Activ_Clte;

    [RfcField(AbapName = "ACTIVACION_LINEA", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 254)]
    [XmlElement("ACTIVACION_LINEA")]
    public string Activacion_Linea
    { 
       get
       {
          return _Activacion_Linea;
       }
       set
       {
          _Activacion_Linea = value;
       }
    }
    private string _Activacion_Linea;

    [RfcField(AbapName = "PEDIDO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 255)]
    [XmlElement("PEDIDO")]
    public string Pedido
    { 
       get
       {
          return _Pedido;
       }
       set
       {
          _Pedido = value;
       }
    }
    private string _Pedido;

    [RfcField(AbapName = "NRO_DEP_GARANTIA", RfcType = RFCTYPE.RFCTYPE_NUM, Length = 10, Offset = 265)]
    [XmlElement("NRO_DEP_GARANTIA")]
    public string Nro_Dep_Garantia
    { 
       get
       {
          return _Nro_Dep_Garantia;
       }
       set
       {
          _Nro_Dep_Garantia = value;
       }
    }
    private string _Nro_Dep_Garantia;

    [RfcField(AbapName = "NRO_REF_DEP_GAR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 16, Offset = 275)]
    [XmlElement("NRO_REF_DEP_GAR")]
    public string Nro_Ref_Dep_Gar
    { 
       get
       {
          return _Nro_Ref_Dep_Gar;
       }
       set
       {
          _Nro_Ref_Dep_Gar = value;
       }
    }
    private string _Nro_Ref_Dep_Gar;

    [RfcField(AbapName = "IND_REQ_CONTRATO", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 291)]
    [XmlElement("IND_REQ_CONTRATO")]
    public string Ind_Req_Contrato
    { 
       get
       {
          return _Ind_Req_Contrato;
       }
       set
       {
          _Ind_Req_Contrato = value;
       }
    }
    private string _Ind_Req_Contrato;

    [RfcField(AbapName = "NRO_REF_CORNER", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 40, Offset = 292)]
    [XmlElement("NRO_REF_CORNER")]
    public string Nro_Ref_Corner
    { 
       get
       {
          return _Nro_Ref_Corner;
       }
       set
       {
          _Nro_Ref_Corner = value;
       }
    }
    private string _Nro_Ref_Corner;

    [RfcField(AbapName = "NUMBR", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 10, Offset = 332)]
    [XmlElement("NUMBR")]
    public string Numbr
    { 
       get
       {
          return _Numbr;
       }
       set
       {
          _Numbr = value;
       }
    }
    private string _Numbr;

    [RfcField(AbapName = "ES_VTA_BUSINESS", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 1, Offset = 342)]
    [XmlElement("ES_VTA_BUSINESS")]
    public string Es_Vta_Business
    { 
       get
       {
          return _Es_Vta_Business;
       }
       set
       {
          _Es_Vta_Business = value;
       }
    }
    private string _Es_Vta_Business;

  }

}
