
//------------------------------------------------------------------------------
// 
//     This code was generated by a SAP. NET Connector Proxy Generator Version 1.0
//     Created at 19/09/2013
//     Created from Windows 2000
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// 
//------------------------------------------------------------------------------
using System;
using System.Text;
using System.Collections;
using System.Runtime.InteropServices;
using System.Xml.Serialization;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using SAP.Connector;

namespace Claro.SisAct.SapGeneral
{

  [RfcStructure(AbapName ="ZWA_UTILIZACION_1" , Length = 29)]
  public class ZWA_UTILIZACION_1 : SAPStructure
  {
    
    [RfcField(AbapName = "ABRVW", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 3, Offset = 0)]
    [XmlElement("ABRVW")]
    public string Abrvw
    { 
       get
       {
          return _Abrvw;
       }
       set
       {
          _Abrvw = value;
       }
    }
    private string _Abrvw;

    [RfcField(AbapName = "BEZEI", RfcType = RFCTYPE.RFCTYPE_CHAR, Length = 20, Offset = 3)]
    [XmlElement("BEZEI")]
    public string Bezei
    { 
       get
       {
          return _Bezei;
       }
       set
       {
          _Bezei = value;
       }
    }
    private string _Bezei;

    [RfcField(AbapName = "PRECIOIGV", RfcType = RFCTYPE.RFCTYPE_BCD, Length = 6, Decimals = 2, Offset = 23)]
    [XmlElement("PRECIOIGV")]
    public Decimal Precioigv
    { 
       get
       {
          return _Precioigv;
       }
       set
       {
          _Precioigv = value;
       }
    }
    private Decimal _Precioigv;

  }

}
