'------------------------------------------------------------------------------
' <autogenerated>
'     This code was generated by a tool.
'     Runtime Version: 1.1.4322.573
'
'     Changes to this file may cause incorrect behavior and will be lost if 
'     the code is regenerated.
' </autogenerated>
'------------------------------------------------------------------------------

Option Strict Off
Option Explicit On

Imports System
Imports System.ComponentModel
Imports System.Diagnostics
Imports System.Web.Services
Imports System.Web.Services.Protocols
Imports System.Xml.Serialization

'
'This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.573.
'
Namespace WS_IN2
    
    '<remarks/>
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.ComponentModel.DesignerCategoryAttribute("code"),  _
     System.Web.Services.WebServiceBindingAttribute(Name:="EbsTfiWSSoapBinding", [Namespace]:="http://pe.com.claro.esb.services")>  _
    Public Class EbsTfiWS
        Inherits System.Web.Services.Protocols.SoapHttpClientProtocol
        
        '<remarks/>
        Public Sub New()
            MyBase.New
            Me.Url = "http://limdeseaiv03.tim.com.pe:8909/TFIWS/EbsTfiWS"
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe.com.claro.esb.services", ResponseNamespace:="http://pe.com.claro.esb.services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub realizarValidacionZMU()
            Me.Invoke("realizarValidacionZMU", New Object(-1) {})
        End Sub
        
        '<remarks/>
        Public Function BeginrealizarValidacionZMU(ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("realizarValidacionZMU", New Object(-1) {}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndrealizarValidacionZMU(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe.com.claro.esb.services", ResponseNamespace:="http://pe.com.claro.esb.services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarDesactivacionTFI(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> ByVal INDatosLineaRequest As INDatosLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("INDatosLineaResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> INDatosLineaResponse
            Dim results() As Object = Me.Invoke("ejecutarDesactivacionTFI", New Object() {INDatosLineaRequest})
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarDesactivacionTFI(ByVal INDatosLineaRequest As INDatosLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarDesactivacionTFI", New Object() {INDatosLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarDesactivacionTFI(ByVal asyncResult As System.IAsyncResult) As INDatosLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe.com.claro.esb.services", ResponseNamespace:="http://pe.com.claro.esb.services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Sub leerArchivosZm(<System.Xml.Serialization.XmlAnyElementAttribute()> ByVal Any As System.Xml.XmlElement, <System.Xml.Serialization.XmlArrayItemAttribute("JavaLangstring")> ByVal files() As String)
            Me.Invoke("leerArchivosZm", New Object() {Any, files})
        End Sub
        
        '<remarks/>
        Public Function BeginleerArchivosZm(ByVal Any As System.Xml.XmlElement, ByVal files() As String, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("leerArchivosZm", New Object() {Any, files}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Sub EndleerArchivosZm(ByVal asyncResult As System.IAsyncResult)
            Me.EndInvoke(asyncResult)
        End Sub
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe.com.claro.esb.services", ResponseNamespace:="http://pe.com.claro.esb.services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarActivacionTFI(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> ByVal TFIRequest As TFIRequest) As <System.Xml.Serialization.XmlElementAttribute("TFIResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> TFIResponse
            Dim results() As Object = Me.Invoke("ejecutarActivacionTFI", New Object() {TFIRequest})
            Return CType(results(0),TFIResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarActivacionTFI(ByVal TFIRequest As TFIRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarActivacionTFI", New Object() {TFIRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarActivacionTFI(ByVal asyncResult As System.IAsyncResult) As TFIResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),TFIResponse)
        End Function
        
        '<remarks/>
        <System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace:="http://pe.com.claro.esb.services", ResponseNamespace:="http://pe.com.claro.esb.services", Use:=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle:=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)>  _
        Public Function ejecutarReactivacionTFI(<System.Xml.Serialization.XmlElementAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> ByVal INDatosLineaRequest As INDatosLineaRequest) As <System.Xml.Serialization.XmlElementAttribute("INDatosLineaResponse", [Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")> INDatosLineaResponse
            Dim results() As Object = Me.Invoke("ejecutarReactivacionTFI", New Object() {INDatosLineaRequest})
            Return CType(results(0),INDatosLineaResponse)
        End Function
        
        '<remarks/>
        Public Function BeginejecutarReactivacionTFI(ByVal INDatosLineaRequest As INDatosLineaRequest, ByVal callback As System.AsyncCallback, ByVal asyncState As Object) As System.IAsyncResult
            Return Me.BeginInvoke("ejecutarReactivacionTFI", New Object() {INDatosLineaRequest}, callback, asyncState)
        End Function
        
        '<remarks/>
        Public Function EndejecutarReactivacionTFI(ByVal asyncResult As System.IAsyncResult) As INDatosLineaResponse
            Dim results() As Object = Me.EndInvoke(asyncResult)
            Return CType(results(0),INDatosLineaResponse)
        End Function
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")>  _
    Public Class INDatosLineaRequest
        
        '<remarks/>
        Public telefono As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")>  _
    Public Class TFIResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")>  _
    Public Class TFIRequest
        
        '<remarks/>
        Public telefono As String
        
        '<remarks/>
        Public opcion As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")>  _
    Public Class DatosLinea
        
        '<remarks/>
        Public providerID As String
        
        '<remarks/>
        Public isFirstCallPassed As String
        
        '<remarks/>
        Public isLocked As String
        
        '<remarks/>
        Public subscriberLifeCycleStatus As String
        
        '<remarks/>
        Public subscriberStatus As String
        
        '<remarks/>
        Public expiryDate As String
        
        '<remarks/>
        Public deletionDate As String
    End Class
    
    '<remarks/>
    <System.Xml.Serialization.XmlTypeAttribute([Namespace]:="http://pe/com/claro/esb/services/prepago/in/schemas/InDatosPrepago.xsd")>  _
    Public Class INDatosLineaResponse
        
        '<remarks/>
        Public resultado As String
        
        '<remarks/>
        Public mensaje As String
        
        '<remarks/>
        Public transaccion As String
        
        '<remarks/>
        Public datosLinea As DatosLinea
    End Class
End Namespace
